In [538]:
import pandas as pd
import numpy as np

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
label = pd.read_csv('train_label.csv')

print(train.head())

      id  amount_tsh date_recorded        funder  gps_height     installer  \
0  69572      6000.0    2011-03-14         Roman        1390         Roman
1   8776         0.0    2013-03-06       Grumeti        1399       GRUMETI
2  34310        25.0    2013-02-25  Lottery Club         686  World vision
3  67743         0.0    2013-01-28        Unicef         263        UNICEF
4  19728         0.0    2011-07-13   Action In A           0       Artisan

   longitude   latitude              wpt_name  num_private  \
0  34.938093  -9.856322                  none            0
1  34.698766  -2.147466              Zahanati            0
2  37.460664  -3.821329           Kwa Mahundi            0
3  38.486161 -11.155298  Zahanati Ya Nanyumbu            0
4  31.130847  -1.825359               Shuleni            0

           ...          payment_type water_quality quality_group  \
0          ...              annually          soft          good
1          ...             never pay          soft          good
2          ...            per bucket          soft          good
3          ...             never pay          soft          good
4          ...             never pay          soft          good

       quantity  quantity_group                source           source_type  \
0        enough          enough                spring                spring
1  insufficient    insufficient  rainwater harvesting  rainwater harvesting
2        enough          enough                   dam                   dam
3           dry             dry           machine dbh              borehole
4      seasonal        seasonal  rainwater harvesting  rainwater harvesting

   source_class              waterpoint_type waterpoint_type_group
0   groundwater           communal standpipe    communal standpipe
1       surface           communal standpipe    communal standpipe
2       surface  communal standpipe multiple    communal standpipe
3   groundwater  communal standpipe multiple    communal standpipe
4       surface           communal standpipe    communal standpipe

[5 rows x 40 columns]

In [539]:
print(train.shape)
print(test.shape)
print(len(test))
print(len(label))
print(label.shape)
data = train.append(test,ignore_index=True)
data.head()

(59400, 40)
(14850, 40)
14850
59400
(59400, 2)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [540]:
# functional - 水点正常运行，无需维修                                1
# functional needs repair - 水点正在运行，但需要维修                 0  
# non functional - 水点无法运作

status_groupDf = pd.DataFrame()
status_groupDf= pd.get_dummies(label['status_group'],prefix='status_group')
label = pd.concat([label,status_groupDf],axis=1)


label_mapDict = {'functional':1,'non functional':-1,'functional needs repair':0}
label['status_group'] = label['status_group'].map(label_mapDict)

label

,id,status_group,status_group_functional,status_group_functional needs repair,status_group_non functional
0,69572,1,1,0,0
1,8776,1,1,0,0
2,34310,1,1,0,0
3,67743,-1,0,0,1
4,19728,1,1,0,0
5,9944,1,1,0,0
6,19816,-1,0,0,1
7,54551,-1,0,0,1
8,53934,-1,0,0,1
9,46144,1,1,0,0
10,49056,1,1,0,0
11,50409,1,1,0,0
12,36957,1,1,0,0
13,50495,1,1,0,0
14,53752,1,1,0,0
15,61848,1,1,0,0
16,48451,-1,0,0,1
17,58155,-1,0,0,1
18,34169,0,0,1,0
19,18274,1,1,0,0
20,48375,1,1,0,0
21,6091,1,1,0,0
22,58500,0,0,1,0
23,37862,1,1,0,0
24,51058,1,1,0,0
25,22308,0,0,1,0
26,55012,1,1,0,0
27,20145,1,1,0,0
28,19685,-1,0,0,1
29,69124,1,1,0,0
...,...,...,...,...,...
59370,14796,1,1,0,0
59371,20387,-1,0,0,1
59372,29940,-1,0,0,1
59373,15233,1,1,0,0
59374,49651,1,1,0,0
59375,50998,1,1,0,0
59376,34716,-1,0,0,1
59377,43986,-1,0,0,1
59378,38067,1,1,0,0
59379,58255,1,1,0,0
59380,30647,-1,0,0,1
59381,67885,-1,0,0,1
59382,47002,-1,0,0,1
59383,44616,1,1,0,0
59384,72148,-1,0,0,1
59385,34473,1,1,0,0
59386,34952,1,1,0,0
59387,26640,1,1,0,0
59388,72559,1,1,0,0
59389,30410,1,1,0,0
59390,13677,1,1,0,0
59391,44885,-1,0,0,1
59392,40607,-1,0,0,1
59393,48348,1,1,0,0
59394,11164,-1,0,0,1
59395,60739,1,1,0,0
59396,27263,1,1,0,0
59397,37057,1,1,0,0
59398,31282,1,1,0,0
59399,26348,1,1,0,0

In [541]:
from collections import Counter

nan_feature = ['funder','installer','subvillage','public_meeting','scheme_management','scheme_name','permit']

print(data['funder'].value_counts())

data['funder'] = data['funder'].fillna('Government Of Tanzania')

data.info()

# funder = Counter(data['funder'])
# funder

Government Of Tanzania       11299
Danida                        3907
Hesawa                        2782
Rwssp                         1703
World Bank                    1701
Kkkt                          1623
World Vision                  1562
Unicef                        1324
Tasaf                         1136
Dhv                           1065
District Council              1037
Private Individual            1034
Dwsp                          1012
0                              980
Norad                          949
Germany Republi                765
Water                          739
Tcrs                           735
Ministry Of Water              728
Dwe                            605
Netherlands                    592
Hifab                          577
Adb                            551
Lga                            546
Amref                          525
Fini Water                     474
Oxfam                          436
Wateraid                       416
Rc Church                      410
Rudep                          390
                             ...
Norad/japan                      1
Pankrasi                         1
Jamal                            1
Norway Aid                       1
Cathoric                         1
Wamakapuchini                    1
Tasae                            1
Mzee Shindika                    1
Chuo                             1
Bong-kug Ohh/choonlza Lee        1
Heasawa                          1
Qwick Win                        1
Mboni Salehe                     1
Selikali Ya Kijiji               1
Dominiki Simwen                  1
Selestine Mganga                 1
Jeshi La Wokovu [cida]           1
Chiko In                         1
Gdp                              1
Da Unoperaio Siciliano           1
Mtambo                           1
Rafael Michael                   1
Boazi /o                         1
Swedish Tandala Project          1
Unicrf                           1
Piscop                           1
Sido                             1
Masai Land                       1
Norani                           1
Village Contributio              1
Name: funder, Length: 2140, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74250 entries, 0 to 74249
Data columns (total 40 columns):
id                       74250 non-null int64
amount_tsh               74250 non-null float64
date_recorded            74250 non-null object
funder                   74250 non-null object
gps_height               74250 non-null int64
installer                69718 non-null object
longitude                74250 non-null float64
latitude                 74250 non-null float64
wpt_name                 74250 non-null object
num_private              74250 non-null int64
basin                    74250 non-null object
subvillage               73780 non-null object
region                   74250 non-null object
region_code              74250 non-null int64
district_code            74250 non-null int64
lga                      74250 non-null object
ward                     74250 non-null object
population               74250 non-null int64
public_meeting           70095 non-null object
recorded_by              74250 non-null object
scheme_management        69404 non-null object
scheme_name              38992 non-null object
permit                   70457 non-null object
construction_year        74250 non-null int64
extraction_type          74250 non-null object
extraction_type_group    74250 non-null object
extraction_type_class    74250 non-null object
management               74250 non-null object
management_group         74250 non-null object
payment                  74250 non-null object
payment_type             74250 non-null object
water_quality            74250 non-null object
quality_group            74250 non-null object
quantity                 74250 non-null object
quantity_group           74250 non-null object
source                   74250 non-null object
source_type              74250 non-null object
source_class             74250 non-null object
waterpoint_type          74250 non-null object
waterpoint_type_group    74250 non-null object
dtypes: float64(3), int64(7), object(30)
memory usage: 22.7+ MB

In [542]:
data['installer'].value_counts()

data['installer'] = data['installer'].fillna('DWE')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74250 entries, 0 to 74249
Data columns (total 40 columns):
id                       74250 non-null int64
amount_tsh               74250 non-null float64
date_recorded            74250 non-null object
funder                   74250 non-null object
gps_height               74250 non-null int64
installer                74250 non-null object
longitude                74250 non-null float64
latitude                 74250 non-null float64
wpt_name                 74250 non-null object
num_private              74250 non-null int64
basin                    74250 non-null object
subvillage               73780 non-null object
region                   74250 non-null object
region_code              74250 non-null int64
district_code            74250 non-null int64
lga                      74250 non-null object
ward                     74250 non-null object
population               74250 non-null int64
public_meeting           70095 non-null object
recorded_by              74250 non-null object
scheme_management        69404 non-null object
scheme_name              38992 non-null object
permit                   70457 non-null object
construction_year        74250 non-null int64
extraction_type          74250 non-null object
extraction_type_group    74250 non-null object
extraction_type_class    74250 non-null object
management               74250 non-null object
management_group         74250 non-null object
payment                  74250 non-null object
payment_type             74250 non-null object
water_quality            74250 non-null object
quality_group            74250 non-null object
quantity                 74250 non-null object
quantity_group           74250 non-null object
source                   74250 non-null object
source_type              74250 non-null object
source_class             74250 non-null object
waterpoint_type          74250 non-null object
waterpoint_type_group    74250 non-null object
dtypes: float64(3), int64(7), object(30)
memory usage: 22.7+ MB

In [543]:
data['subvillage'].value_counts() 

data['subvillage'] = data['subvillage'].fillna(axis=0,method='ffill')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74250 entries, 0 to 74249
Data columns (total 40 columns):
id                       74250 non-null int64
amount_tsh               74250 non-null float64
date_recorded            74250 non-null object
funder                   74250 non-null object
gps_height               74250 non-null int64
installer                74250 non-null object
longitude                74250 non-null float64
latitude                 74250 non-null float64
wpt_name                 74250 non-null object
num_private              74250 non-null int64
basin                    74250 non-null object
subvillage               74250 non-null object
region                   74250 non-null object
region_code              74250 non-null int64
district_code            74250 non-null int64
lga                      74250 non-null object
ward                     74250 non-null object
population               74250 non-null int64
public_meeting           70095 non-null object
recorded_by              74250 non-null object
scheme_management        69404 non-null object
scheme_name              38992 non-null object
permit                   70457 non-null object
construction_year        74250 non-null int64
extraction_type          74250 non-null object
extraction_type_group    74250 non-null object
extraction_type_class    74250 non-null object
management               74250 non-null object
management_group         74250 non-null object
payment                  74250 non-null object
payment_type             74250 non-null object
water_quality            74250 non-null object
quality_group            74250 non-null object
quantity                 74250 non-null object
quantity_group           74250 non-null object
source                   74250 non-null object
source_type              74250 non-null object
source_class             74250 non-null object
waterpoint_type          74250 non-null object
waterpoint_type_group    74250 non-null object
dtypes: float64(3), int64(7), object(30)
memory usage: 22.7+ MB

In [544]:
data['public_meeting'].value_counts()
data['public_meeting'] = data['public_meeting'].fillna(axis=0,method='ffill')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74250 entries, 0 to 74249
Data columns (total 40 columns):
id                       74250 non-null int64
amount_tsh               74250 non-null float64
date_recorded            74250 non-null object
funder                   74250 non-null object
gps_height               74250 non-null int64
installer                74250 non-null object
longitude                74250 non-null float64
latitude                 74250 non-null float64
wpt_name                 74250 non-null object
num_private              74250 non-null int64
basin                    74250 non-null object
subvillage               74250 non-null object
region                   74250 non-null object
region_code              74250 non-null int64
district_code            74250 non-null int64
lga                      74250 non-null object
ward                     74250 non-null object
population               74250 non-null int64
public_meeting           74250 non-null bool
recorded_by              74250 non-null object
scheme_management        69404 non-null object
scheme_name              38992 non-null object
permit                   70457 non-null object
construction_year        74250 non-null int64
extraction_type          74250 non-null object
extraction_type_group    74250 non-null object
extraction_type_class    74250 non-null object
management               74250 non-null object
management_group         74250 non-null object
payment                  74250 non-null object
payment_type             74250 non-null object
water_quality            74250 non-null object
quality_group            74250 non-null object
quantity                 74250 non-null object
quantity_group           74250 non-null object
source                   74250 non-null object
source_type              74250 non-null object
source_class             74250 non-null object
waterpoint_type          74250 non-null object
waterpoint_type_group    74250 non-null object
dtypes: bool(1), float64(3), int64(7), object(29)
memory usage: 22.2+ MB

In [545]:
data['scheme_management'].value_counts()
data['scheme_management'] = data['scheme_management'].fillna('VWC')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74250 entries, 0 to 74249
Data columns (total 40 columns):
id                       74250 non-null int64
amount_tsh               74250 non-null float64
date_recorded            74250 non-null object
funder                   74250 non-null object
gps_height               74250 non-null int64
installer                74250 non-null object
longitude                74250 non-null float64
latitude                 74250 non-null float64
wpt_name                 74250 non-null object
num_private              74250 non-null int64
basin                    74250 non-null object
subvillage               74250 non-null object
region                   74250 non-null object
region_code              74250 non-null int64
district_code            74250 non-null int64
lga                      74250 non-null object
ward                     74250 non-null object
population               74250 non-null int64
public_meeting           74250 non-null bool
recorded_by              74250 non-null object
scheme_management        74250 non-null object
scheme_name              38992 non-null object
permit                   70457 non-null object
construction_year        74250 non-null int64
extraction_type          74250 non-null object
extraction_type_group    74250 non-null object
extraction_type_class    74250 non-null object
management               74250 non-null object
management_group         74250 non-null object
payment                  74250 non-null object
payment_type             74250 non-null object
water_quality            74250 non-null object
quality_group            74250 non-null object
quantity                 74250 non-null object
quantity_group           74250 non-null object
source                   74250 non-null object
source_type              74250 non-null object
source_class             74250 non-null object
waterpoint_type          74250 non-null object
waterpoint_type_group    74250 non-null object
dtypes: bool(1), float64(3), int64(7), object(29)
memory usage: 22.2+ MB

In [546]:
data = data.drop(['scheme_name'],axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74250 entries, 0 to 74249
Data columns (total 39 columns):
id                       74250 non-null int64
amount_tsh               74250 non-null float64
date_recorded            74250 non-null object
funder                   74250 non-null object
gps_height               74250 non-null int64
installer                74250 non-null object
longitude                74250 non-null float64
latitude                 74250 non-null float64
wpt_name                 74250 non-null object
num_private              74250 non-null int64
basin                    74250 non-null object
subvillage               74250 non-null object
region                   74250 non-null object
region_code              74250 non-null int64
district_code            74250 non-null int64
lga                      74250 non-null object
ward                     74250 non-null object
population               74250 non-null int64
public_meeting           74250 non-null bool
recorded_by              74250 non-null object
scheme_management        74250 non-null object
permit                   70457 non-null object
construction_year        74250 non-null int64
extraction_type          74250 non-null object
extraction_type_group    74250 non-null object
extraction_type_class    74250 non-null object
management               74250 non-null object
management_group         74250 non-null object
payment                  74250 non-null object
payment_type             74250 non-null object
water_quality            74250 non-null object
quality_group            74250 non-null object
quantity                 74250 non-null object
quantity_group           74250 non-null object
source                   74250 non-null object
source_type              74250 non-null object
source_class             74250 non-null object
waterpoint_type          74250 non-null object
waterpoint_type_group    74250 non-null object
dtypes: bool(1), float64(3), int64(7), object(28)
memory usage: 21.6+ MB

In [547]:
data['permit'].value_counts()
data['permit'] = data['permit'].fillna(axis=0,method='ffill')

In [548]:
# 特征提取
print(data['public_meeting']+0)

data['public_meeting'] = data['public_meeting'] + 0
# print(data['public_metting'])
# data['public_meeting'] = data['public_meeting'] + 0
# data['public_metting']

# public_meeting_mapDict = {'True':1,'False':0}
# data['public_meeting'] = data['public_meeting'].map(public_meeting_mapDict)
# print(data['public_meeting'])

0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       0
25       1
26       0
27       1
28       1
29       1
        ..
74220    1
74221    1
74222    1
74223    1
74224    1
74225    1
74226    1
74227    1
74228    0
74229    0
74230    1
74231    1
74232    1
74233    1
74234    1
74235    1
74236    1
74237    1
74238    1
74239    1
74240    1
74241    1
74242    1
74243    1
74244    1
74245    1
74246    1
74247    1
74248    1
74249    1
Name: public_meeting, Length: 74250, dtype: int32

In [549]:
from collections import Counter
Counter(data['waterpoint_type_group'])

waterpoint_type_groupDf = pd.DataFrame()
waterpoint_type_groupDf = pd.get_dummies(data['waterpoint_type_group'],prefix='waterpoint_type_group')
data = pd.concat([data,waterpoint_type_groupDf],axis=1)
data.drop('waterpoint_type_group',axis=1,inplace=True)
data

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,source,source_type,source_class,waterpoint_type,waterpoint_type_group_cattle trough,waterpoint_type_group_communal standpipe,waterpoint_type_group_dam,waterpoint_type_group_hand pump,waterpoint_type_group_improved spring,waterpoint_type_group_other
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,...,rainwater harvesting,rainwater harvesting,surface,communal standpipe,0,1,0,0,0,0
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,...,dam,dam,surface,communal standpipe multiple,0,1,0,0,0,0
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,...,machine dbh,borehole,groundwater,communal standpipe multiple,0,1,0,0,0,0
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,...,rainwater harvesting,rainwater harvesting,surface,communal standpipe,0,1,0,0,0,0
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,...,other,other,unknown,communal standpipe multiple,0,1,0,0,0,0
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,...,machine dbh,borehole,groundwater,hand pump,0,0,0,1,0,0
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,...,machine dbh,borehole,groundwater,hand pump,0,0,0,1,0,0
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,...,machine dbh,borehole,groundwater,other,0,0,0,0,0,1
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,...,machine dbh,borehole,groundwater,hand pump,0,0,0,1,0,0
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,...,spring,spring,groundwater,other,0,0,0,0,0,1
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,...,spring,spring,groundwater,improved spring,0,0,0,0,1,0
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,...,machine dbh,borehole,groundwater,hand pump,0,0,0,1,0,0
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,52228,0.0,2013-01-27,Dbfpe,265,DBFPE,38.504640,-1.016990e+01,Shule Ya Msingi Mayaka,0,...,rainwater harvesting,rainwater harvesting,surface,communal standpipe,0,1,0,0,0,0
74221,70038,5.0,2013-03-29,Ces (gmbh),1322,DWE,37.261731,-3.235687e+00,Kwa Leonard Soka,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
74222,25901,50.0,2013-01-22,Lga,640,LGA,39.297410,-1.092504e+01,Tangini,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74223,21131,0.0,2011-04-03,Government Of Tanzania,0,DWE,33.918953,-9.298466e+00,Ndubi,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74224,26580,0.0,2011-04-20,Po,574,Po,37.070462,-6.575076e+00,Mwanji,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74225,66059,0.0,2013-02-02,Fin Water,331,FIN WATER,38.761961,-1.091314e+01,Mkwajuni,0,...,machine dbh,borehole,groundwater,hand pump,0,0,0,1,0,0
74226,32944,0.0,2012-10-24,World Vision,0,World vision,32.243937,-3.311621e+00,Umoja,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74227,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74228,8471,50.0,2011-02-20,Private,78,Private,39.254272,-7.060921e+00,Mkopi,0,...,machine dbh,borehole,groundwater,other,0,0,0,0,0,1
74229,19620,0.0,2013-01-03,Government Of Tanzania,836,Government,35.227320,-1.103905e+01,Kituo Ch Afya,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74230,74162,0.0,2013-03-19,Tcrs,1651,TCRS,37.962243,-4.494348e+00,Kwa Andrew,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74231,37994,0.0,2012-10-26,Hesawa,0,DWE,0.000000,-2.000000e-08,Kwa Masilili,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74232,71151,0.0,2013-03-25,Kkkt,1393,KKKT,36.930169,-3.255077e+00,Tankini,0,...,machine dbh,borehole,groundwater,communal standpipe,0,1,0,0,0,0
74233,45017,1000.0,2011-03-05,Kkkt,1729,Commu,34.302104,-9.455737e+00,none,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74234,12592,0.0,2011-03-27,Kirde,0,DWE,35.840727,-4.633272e+00,Kwa Mrangi,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74235,58693,0.0,2013-01-25,Rwssp,0,DWE,32.442886,-3.644662e+00,Busangi,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74236,57539,0.0,2011-03-18,Amref,-7,AMREF,39.140091,-7.477423e+00,Nyamalonda,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74237,71252,500.0,2013-02-10,Tasaf,1241,TASAF,30.114667,-4.162845e+00,Pentecoste Church,0,...,machine dbh,borehole,groundwater,hand pump,0,0,0,1,0,0
74238,7869,3000.0,2011-03-11,Kkkt,2046,Commu,34.345525,-9.547077e+00,none,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74239,57316,0.0,2011-03-11,Devon Aid Korogwe,347,Local technician,38.613415,-4.815222e+00,Jahiya,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0
74240,59757,0.0,2013-02-24,Villagers,1291,Villagers,35.345384,-9.831170e+00,Kwa Reonard,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
74241,64579,0.0,2012-10-26,Dwsp,0,DWE,0.000000,-2.000000e-08,Iguna,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74242,57731,600.0,2013-01-27,Isf,808,DWE,29.740224,-4.882705e+00,Hongera,0,...,river,river/lake,surface,communal standpipe multiple,0,1,0,0,0,0
74243,65541,0.0,2013-02-04,Oxfarm,1641,OXFARM,29.768139,-4.480618e+00,Mwandami,0,...,spring,spring,groundwater,other,0,0,0,0,0,1
74244,68174,0.0,2012-11-07,Netherlands,0,DWE,34.096878,-3.079689e+00,Ikanayugu,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74245,39307,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841e+00,Kwambwezi,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
74246,18990,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428e+00,Bonde La Mkondoa,0,...,shallow well,shallow well,groundwater,hand pump,0,0,0,1,0,0
74247,28749,0.0,2013-03-04,Government Of Tanzania,1476,DWE,34.739804,-4.585587e+00,Bwawani,0,...,dam,dam,surface,communal standpipe,0,1,0,0,0,0
74248,33492,0.0,2013-02-18,Germany,998,DWE,35.432732,-1.058416e+01,Kwa John,0,...,river,river/lake,surface,communal standpipe,0,1,0,0,0,0
74249,68707,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-1.122601e+01,Kwa Mzee Chagala,0,...,spring,spring,groundwater,communal standpipe,0,1,0,0,0,0

In [550]:
Counter(data['waterpoint_type'])
waterpoint_typeDf = pd.DataFrame()
waterpoint_typeDf = pd.get_dummies(data['waterpoint_type'],prefix='waterpoint_type')
data = pd.concat([data,waterpoint_typeDf],axis=1)
data.drop('waterpoint_type',axis=1,inplace=True)
data

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,waterpoint_type_group_hand pump,waterpoint_type_group_improved spring,waterpoint_type_group_other,waterpoint_type_cattle trough,waterpoint_type_communal standpipe,waterpoint_type_communal standpipe multiple,waterpoint_type_dam,waterpoint_type_hand pump,waterpoint_type_improved spring,waterpoint_type_other
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,...,0,0,0,0,1,0,0,0,0,0
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,...,0,0,0,0,1,0,0,0,0,0
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,...,0,0,0,0,0,1,0,0,0,0
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,...,0,0,0,0,0,1,0,0,0,0
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,...,0,0,0,0,1,0,0,0,0,0
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,...,0,0,0,0,0,1,0,0,0,0
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,...,1,0,0,0,0,0,0,1,0,0
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,...,1,0,0,0,0,0,0,1,0,0
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,...,1,0,0,0,0,0,0,1,0,0
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,...,1,0,0,0,0,0,0,1,0,0
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,...,0,0,1,0,0,0,0,0,0,1
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,...,1,0,0,0,0,0,0,1,0,0
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,...,1,0,0,0,0,0,0,1,0,0
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,...,0,0,0,0,1,0,0,0,0,0
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,...,1,0,0,0,0,0,0,1,0,0
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,...,1,0,0,0,0,0,0,1,0,0
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,...,0,0,0,0,1,0,0,0,0,0
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,...,0,0,0,0,1,0,0,0,0,0
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,...,0,0,1,0,0,0,0,0,0,1
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,...,0,0,0,0,1,0,0,0,0,0
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,...,0,0,0,0,1,0,0,0,0,0
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,...,1,0,0,0,0,0,0,1,0,0
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,...,0,0,0,0,1,0,0,0,0,0
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,...,0,0,0,0,1,0,0,0,0,0
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,...,0,1,0,0,0,0,0,0,1,0
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,...,0,0,0,0,1,0,0,0,0,0
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,...,1,0,0,0,0,0,0,1,0,0
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,...,1,0,0,0,0,0,0,1,0,0
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,...,0,0,0,0,1,0,0,0,0,0
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,52228,0.0,2013-01-27,Dbfpe,265,DBFPE,38.504640,-1.016990e+01,Shule Ya Msingi Mayaka,0,...,0,0,0,0,1,0,0,0,0,0
74221,70038,5.0,2013-03-29,Ces (gmbh),1322,DWE,37.261731,-3.235687e+00,Kwa Leonard Soka,0,...,0,0,0,0,1,0,0,0,0,0
74222,25901,50.0,2013-01-22,Lga,640,LGA,39.297410,-1.092504e+01,Tangini,0,...,0,0,0,0,1,0,0,0,0,0
74223,21131,0.0,2011-04-03,Government Of Tanzania,0,DWE,33.918953,-9.298466e+00,Ndubi,0,...,0,0,0,0,1,0,0,0,0,0
74224,26580,0.0,2011-04-20,Po,574,Po,37.070462,-6.575076e+00,Mwanji,0,...,1,0,0,0,0,0,0,1,0,0
74225,66059,0.0,2013-02-02,Fin Water,331,FIN WATER,38.761961,-1.091314e+01,Mkwajuni,0,...,1,0,0,0,0,0,0,1,0,0
74226,32944,0.0,2012-10-24,World Vision,0,World vision,32.243937,-3.311621e+00,Umoja,0,...,1,0,0,0,0,0,0,1,0,0
74227,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,1,0,0,0,0,0,0,1,0,0
74228,8471,50.0,2011-02-20,Private,78,Private,39.254272,-7.060921e+00,Mkopi,0,...,0,0,1,0,0,0,0,0,0,1
74229,19620,0.0,2013-01-03,Government Of Tanzania,836,Government,35.227320,-1.103905e+01,Kituo Ch Afya,0,...,0,0,0,0,1,0,0,0,0,0
74230,74162,0.0,2013-03-19,Tcrs,1651,TCRS,37.962243,-4.494348e+00,Kwa Andrew,0,...,0,0,0,0,1,0,0,0,0,0
74231,37994,0.0,2012-10-26,Hesawa,0,DWE,0.000000,-2.000000e-08,Kwa Masilili,0,...,1,0,0,0,0,0,0,1,0,0
74232,71151,0.0,2013-03-25,Kkkt,1393,KKKT,36.930169,-3.255077e+00,Tankini,0,...,0,0,0,0,1,0,0,0,0,0
74233,45017,1000.0,2011-03-05,Kkkt,1729,Commu,34.302104,-9.455737e+00,none,0,...,0,0,0,0,1,0,0,0,0,0
74234,12592,0.0,2011-03-27,Kirde,0,DWE,35.840727,-4.633272e+00,Kwa Mrangi,0,...,0,0,0,0,1,0,0,0,0,0
74235,58693,0.0,2013-01-25,Rwssp,0,DWE,32.442886,-3.644662e+00,Busangi,0,...,1,0,0,0,0,0,0,1,0,0
74236,57539,0.0,2011-03-18,Amref,-7,AMREF,39.140091,-7.477423e+00,Nyamalonda,0,...,1,0,0,0,0,0,0,1,0,0
74237,71252,500.0,2013-02-10,Tasaf,1241,TASAF,30.114667,-4.162845e+00,Pentecoste Church,0,...,1,0,0,0,0,0,0,1,0,0
74238,7869,3000.0,2011-03-11,Kkkt,2046,Commu,34.345525,-9.547077e+00,none,0,...,0,0,0,0,1,0,0,0,0,0
74239,57316,0.0,2011-03-11,Devon Aid Korogwe,347,Local technician,38.613415,-4.815222e+00,Jahiya,0,...,0,0,0,0,1,0,0,0,0,0
74240,59757,0.0,2013-02-24,Villagers,1291,Villagers,35.345384,-9.831170e+00,Kwa Reonard,0,...,0,0,0,0,1,0,0,0,0,0
74241,64579,0.0,2012-10-26,Dwsp,0,DWE,0.000000,-2.000000e-08,Iguna,0,...,1,0,0,0,0,0,0,1,0,0
74242,57731,600.0,2013-01-27,Isf,808,DWE,29.740224,-4.882705e+00,Hongera,0,...,0,0,0,0,0,1,0,0,0,0
74243,65541,0.0,2013-02-04,Oxfarm,1641,OXFARM,29.768139,-4.480618e+00,Mwandami,0,...,0,0,1,0,0,0,0,0,0,1
74244,68174,0.0,2012-11-07,Netherlands,0,DWE,34.096878,-3.079689e+00,Ikanayugu,0,...,1,0,0,0,0,0,0,1,0,0
74245,39307,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841e+00,Kwambwezi,0,...,0,0,0,0,1,0,0,0,0,0
74246,18990,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428e+00,Bonde La Mkondoa,0,...,1,0,0,0,0,0,0,1,0,0
74247,28749,0.0,2013-03-04,Government Of Tanzania,1476,DWE,34.739804,-4.585587e+00,Bwawani,0,...,0,0,0,0,1,0,0,0,0,0
74248,33492,0.0,2013-02-18,Germany,998,DWE,35.432732,-1.058416e+01,Kwa John,0,...,0,0,0,0,1,0,0,0,0,0
74249,68707,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-1.122601e+01,Kwa Mzee Chagala,0,...,0,0,0,0,1,0,0,0,0,0

In [551]:
Counter(data['source_class'])
source_classDf = pd.DataFrame()
source_classDf = pd.get_dummies(data['source_class'],prefix='source_class')
data = pd.concat([data,source_classDf],axis=1)
data.drop('source_class',axis=1,)
data

# 该组数据表示source_class  数据中有347个数据标识为'unknown'
# 另一种方法将unknown替换为空值  然后将其填充

# waterpoint_typeDf = pd.DataFrame()
# waterpoint_typeDf = pd.get_dummies(data['waterpoint_type'],prefix='waterpoint_type')
# data = pd.concat([data,waterpoint_typeDf],axis=1)
# data.drop('waterpoint_type',axis=1,inplace=True)
# data

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,waterpoint_type_cattle trough,waterpoint_type_communal standpipe,waterpoint_type_communal standpipe multiple,waterpoint_type_dam,waterpoint_type_hand pump,waterpoint_type_improved spring,waterpoint_type_other,source_class_groundwater,source_class_surface,source_class_unknown
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,...,0,1,0,0,0,0,0,1,0,0
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,...,0,1,0,0,0,0,0,0,1,0
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,...,0,0,1,0,0,0,0,0,1,0
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,...,0,0,1,0,0,0,0,1,0,0
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,...,0,1,0,0,0,0,0,0,1,0
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,...,0,0,1,0,0,0,0,0,0,1
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,...,0,0,0,0,1,0,0,1,0,0
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,...,0,0,0,0,1,0,0,1,0,0
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,...,0,0,0,0,1,0,0,1,0,0
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,...,0,0,0,0,1,0,0,1,0,0
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,...,0,0,0,0,0,0,1,1,0,0
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,...,0,0,0,0,1,0,0,1,0,0
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,...,0,0,0,0,1,0,0,1,0,0
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,...,0,1,0,0,0,0,0,1,0,0
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,...,0,0,0,0,1,0,0,1,0,0
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,...,0,0,0,0,1,0,0,1,0,0
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,...,0,1,0,0,0,0,0,0,1,0
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,...,0,1,0,0,0,0,0,0,1,0
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,...,0,0,0,0,0,0,1,1,0,0
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,...,0,1,0,0,0,0,0,1,0,0
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,...,0,1,0,0,0,0,0,1,0,0
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,...,0,0,0,0,1,0,0,1,0,0
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,...,0,1,0,0,0,0,0,0,1,0
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,...,0,1,0,0,0,0,0,0,1,0
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,...,0,0,0,0,0,1,0,1,0,0
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,...,0,1,0,0,0,0,0,1,0,0
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,...,0,0,0,0,1,0,0,1,0,0
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,...,0,0,0,0,1,0,0,1,0,0
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,...,0,1,0,0,0,0,0,1,0,0
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,52228,0.0,2013-01-27,Dbfpe,265,DBFPE,38.504640,-1.016990e+01,Shule Ya Msingi Mayaka,0,...,0,1,0,0,0,0,0,0,1,0
74221,70038,5.0,2013-03-29,Ces (gmbh),1322,DWE,37.261731,-3.235687e+00,Kwa Leonard Soka,0,...,0,1,0,0,0,0,0,0,1,0
74222,25901,50.0,2013-01-22,Lga,640,LGA,39.297410,-1.092504e+01,Tangini,0,...,0,1,0,0,0,0,0,1,0,0
74223,21131,0.0,2011-04-03,Government Of Tanzania,0,DWE,33.918953,-9.298466e+00,Ndubi,0,...,0,1,0,0,0,0,0,1,0,0
74224,26580,0.0,2011-04-20,Po,574,Po,37.070462,-6.575076e+00,Mwanji,0,...,0,0,0,0,1,0,0,1,0,0
74225,66059,0.0,2013-02-02,Fin Water,331,FIN WATER,38.761961,-1.091314e+01,Mkwajuni,0,...,0,0,0,0,1,0,0,1,0,0
74226,32944,0.0,2012-10-24,World Vision,0,World vision,32.243937,-3.311621e+00,Umoja,0,...,0,0,0,0,1,0,0,1,0,0
74227,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,0,0,0,0,1,0,0,1,0,0
74228,8471,50.0,2011-02-20,Private,78,Private,39.254272,-7.060921e+00,Mkopi,0,...,0,0,0,0,0,0,1,1,0,0
74229,19620,0.0,2013-01-03,Government Of Tanzania,836,Government,35.227320,-1.103905e+01,Kituo Ch Afya,0,...,0,1,0,0,0,0,0,1,0,0
74230,74162,0.0,2013-03-19,Tcrs,1651,TCRS,37.962243,-4.494348e+00,Kwa Andrew,0,...,0,1,0,0,0,0,0,1,0,0
74231,37994,0.0,2012-10-26,Hesawa,0,DWE,0.000000,-2.000000e-08,Kwa Masilili,0,...,0,0,0,0,1,0,0,1,0,0
74232,71151,0.0,2013-03-25,Kkkt,1393,KKKT,36.930169,-3.255077e+00,Tankini,0,...,0,1,0,0,0,0,0,1,0,0
74233,45017,1000.0,2011-03-05,Kkkt,1729,Commu,34.302104,-9.455737e+00,none,0,...,0,1,0,0,0,0,0,1,0,0
74234,12592,0.0,2011-03-27,Kirde,0,DWE,35.840727,-4.633272e+00,Kwa Mrangi,0,...,0,1,0,0,0,0,0,1,0,0
74235,58693,0.0,2013-01-25,Rwssp,0,DWE,32.442886,-3.644662e+00,Busangi,0,...,0,0,0,0,1,0,0,1,0,0
74236,57539,0.0,2011-03-18,Amref,-7,AMREF,39.140091,-7.477423e+00,Nyamalonda,0,...,0,0,0,0,1,0,0,1,0,0
74237,71252,500.0,2013-02-10,Tasaf,1241,TASAF,30.114667,-4.162845e+00,Pentecoste Church,0,...,0,0,0,0,1,0,0,1,0,0
74238,7869,3000.0,2011-03-11,Kkkt,2046,Commu,34.345525,-9.547077e+00,none,0,...,0,1,0,0,0,0,0,1,0,0
74239,57316,0.0,2011-03-11,Devon Aid Korogwe,347,Local technician,38.613415,-4.815222e+00,Jahiya,0,...,0,1,0,0,0,0,0,1,0,0
74240,59757,0.0,2013-02-24,Villagers,1291,Villagers,35.345384,-9.831170e+00,Kwa Reonard,0,...,0,1,0,0,0,0,0,0,1,0
74241,64579,0.0,2012-10-26,Dwsp,0,DWE,0.000000,-2.000000e-08,Iguna,0,...,0,0,0,0,1,0,0,1,0,0
74242,57731,600.0,2013-01-27,Isf,808,DWE,29.740224,-4.882705e+00,Hongera,0,...,0,0,1,0,0,0,0,0,1,0
74243,65541,0.0,2013-02-04,Oxfarm,1641,OXFARM,29.768139,-4.480618e+00,Mwandami,0,...,0,0,0,0,0,0,1,1,0,0
74244,68174,0.0,2012-11-07,Netherlands,0,DWE,34.096878,-3.079689e+00,Ikanayugu,0,...,0,0,0,0,1,0,0,1,0,0
74245,39307,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841e+00,Kwambwezi,0,...,0,1,0,0,0,0,0,0,1,0
74246,18990,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428e+00,Bonde La Mkondoa,0,...,0,0,0,0,1,0,0,1,0,0
74247,28749,0.0,2013-03-04,Government Of Tanzania,1476,DWE,34.739804,-4.585587e+00,Bwawani,0,...,0,1,0,0,0,0,0,0,1,0
74248,33492,0.0,2013-02-18,Germany,998,DWE,35.432732,-1.058416e+01,Kwa John,0,...,0,1,0,0,0,0,0,0,1,0
74249,68707,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-1.122601e+01,Kwa Mzee Chagala,0,...,0,1,0,0,0,0,0,1,0,0

In [552]:
Counter(data['source_type'])
source_typeDf = pd.DataFrame()
source_typeDf = pd.get_dummies(data['source_type'],prefix='source_type')
data = pd.concat([data,source_typeDf],axis=1)
data.drop('source_type',axis=1,)
data

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,source_class_groundwater,source_class_surface,source_class_unknown,source_type_borehole,source_type_dam,source_type_other,source_type_rainwater harvesting,source_type_river/lake,source_type_shallow well,source_type_spring
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,...,1,0,0,0,0,0,0,0,0,1
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,...,0,1,0,0,0,0,1,0,0,0
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,...,0,1,0,0,1,0,0,0,0,0
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,...,1,0,0,1,0,0,0,0,0,0
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,...,0,1,0,0,0,0,1,0,0,0
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,...,0,0,1,0,0,1,0,0,0,0
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,...,1,0,0,1,0,0,0,0,0,0
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,...,1,0,0,0,0,0,0,0,1,0
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,...,1,0,0,1,0,0,0,0,0,0
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,...,1,0,0,0,0,0,0,0,1,0
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,...,1,0,0,1,0,0,0,0,0,0
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,...,1,0,0,0,0,0,0,0,1,0
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,...,1,0,0,0,0,0,0,0,1,0
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,...,1,0,0,0,0,0,0,0,0,1
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,...,1,0,0,0,0,0,0,0,1,0
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,...,1,0,0,1,0,0,0,0,0,0
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,...,0,1,0,0,0,0,0,1,0,0
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,...,0,1,0,0,0,0,0,1,0,0
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,...,1,0,0,0,0,0,0,0,0,1
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,...,1,0,0,0,0,0,0,0,0,1
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,...,1,0,0,0,0,0,0,0,0,1
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,...,1,0,0,0,0,0,0,0,1,0
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,...,0,1,0,0,0,0,0,1,0,0
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,...,0,1,0,0,0,0,0,1,0,0
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,...,1,0,0,0,0,0,0,0,0,1
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,...,1,0,0,0,0,0,0,0,0,1
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,...,1,0,0,1,0,0,0,0,0,0
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,...,1,0,0,0,0,0,0,0,1,0
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,...,1,0,0,0,0,0,0,0,0,1
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,52228,0.0,2013-01-27,Dbfpe,265,DBFPE,38.504640,-1.016990e+01,Shule Ya Msingi Mayaka,0,...,0,1,0,0,0,0,1,0,0,0
74221,70038,5.0,2013-03-29,Ces (gmbh),1322,DWE,37.261731,-3.235687e+00,Kwa Leonard Soka,0,...,0,1,0,0,0,0,0,1,0,0
74222,25901,50.0,2013-01-22,Lga,640,LGA,39.297410,-1.092504e+01,Tangini,0,...,1,0,0,0,0,0,0,0,0,1
74223,21131,0.0,2011-04-03,Government Of Tanzania,0,DWE,33.918953,-9.298466e+00,Ndubi,0,...,1,0,0,0,0,0,0,0,0,1
74224,26580,0.0,2011-04-20,Po,574,Po,37.070462,-6.575076e+00,Mwanji,0,...,1,0,0,0,0,0,0,0,1,0
74225,66059,0.0,2013-02-02,Fin Water,331,FIN WATER,38.761961,-1.091314e+01,Mkwajuni,0,...,1,0,0,1,0,0,0,0,0,0
74226,32944,0.0,2012-10-24,World Vision,0,World vision,32.243937,-3.311621e+00,Umoja,0,...,1,0,0,0,0,0,0,0,1,0
74227,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,1,0,0,0,0,0,0,0,1,0
74228,8471,50.0,2011-02-20,Private,78,Private,39.254272,-7.060921e+00,Mkopi,0,...,1,0,0,1,0,0,0,0,0,0
74229,19620,0.0,2013-01-03,Government Of Tanzania,836,Government,35.227320,-1.103905e+01,Kituo Ch Afya,0,...,1,0,0,0,0,0,0,0,0,1
74230,74162,0.0,2013-03-19,Tcrs,1651,TCRS,37.962243,-4.494348e+00,Kwa Andrew,0,...,1,0,0,0,0,0,0,0,0,1
74231,37994,0.0,2012-10-26,Hesawa,0,DWE,0.000000,-2.000000e-08,Kwa Masilili,0,...,1,0,0,0,0,0,0,0,1,0
74232,71151,0.0,2013-03-25,Kkkt,1393,KKKT,36.930169,-3.255077e+00,Tankini,0,...,1,0,0,1,0,0,0,0,0,0
74233,45017,1000.0,2011-03-05,Kkkt,1729,Commu,34.302104,-9.455737e+00,none,0,...,1,0,0,0,0,0,0,0,0,1
74234,12592,0.0,2011-03-27,Kirde,0,DWE,35.840727,-4.633272e+00,Kwa Mrangi,0,...,1,0,0,0,0,0,0,0,0,1
74235,58693,0.0,2013-01-25,Rwssp,0,DWE,32.442886,-3.644662e+00,Busangi,0,...,1,0,0,0,0,0,0,0,1,0
74236,57539,0.0,2011-03-18,Amref,-7,AMREF,39.140091,-7.477423e+00,Nyamalonda,0,...,1,0,0,0,0,0,0,0,1,0
74237,71252,500.0,2013-02-10,Tasaf,1241,TASAF,30.114667,-4.162845e+00,Pentecoste Church,0,...,1,0,0,1,0,0,0,0,0,0
74238,7869,3000.0,2011-03-11,Kkkt,2046,Commu,34.345525,-9.547077e+00,none,0,...,1,0,0,0,0,0,0,0,0,1
74239,57316,0.0,2011-03-11,Devon Aid Korogwe,347,Local technician,38.613415,-4.815222e+00,Jahiya,0,...,1,0,0,0,0,0,0,0,0,1
74240,59757,0.0,2013-02-24,Villagers,1291,Villagers,35.345384,-9.831170e+00,Kwa Reonard,0,...,0,1,0,0,0,0,0,1,0,0
74241,64579,0.0,2012-10-26,Dwsp,0,DWE,0.000000,-2.000000e-08,Iguna,0,...,1,0,0,0,0,0,0,0,1,0
74242,57731,600.0,2013-01-27,Isf,808,DWE,29.740224,-4.882705e+00,Hongera,0,...,0,1,0,0,0,0,0,1,0,0
74243,65541,0.0,2013-02-04,Oxfarm,1641,OXFARM,29.768139,-4.480618e+00,Mwandami,0,...,1,0,0,0,0,0,0,0,0,1
74244,68174,0.0,2012-11-07,Netherlands,0,DWE,34.096878,-3.079689e+00,Ikanayugu,0,...,1,0,0,0,0,0,0,0,1,0
74245,39307,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841e+00,Kwambwezi,0,...,0,1,0,0,0,0,0,1,0,0
74246,18990,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428e+00,Bonde La Mkondoa,0,...,1,0,0,0,0,0,0,0,1,0
74247,28749,0.0,2013-03-04,Government Of Tanzania,1476,DWE,34.739804,-4.585587e+00,Bwawani,0,...,0,1,0,0,1,0,0,0,0,0
74248,33492,0.0,2013-02-18,Germany,998,DWE,35.432732,-1.058416e+01,Kwa John,0,...,0,1,0,0,0,0,0,1,0,0
74249,68707,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-1.122601e+01,Kwa Mzee Chagala,0,...,1,0,0,0,0,0,0,0,0,1

In [553]:
Counter(data['source'])
sourceDf = pd.DataFrame()
sourceDf = pd.get_dummies(data['source'],prefix='sorurce')
data = pd.concat([data,sourceDf],axis=1)
data.drop('source',axis=1)
data

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,sorurce_dam,sorurce_hand dtw,sorurce_lake,sorurce_machine dbh,sorurce_other,sorurce_rainwater harvesting,sorurce_river,sorurce_shallow well,sorurce_spring,sorurce_unknown
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,...,0,0,0,0,0,0,0,0,1,0
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,...,0,0,0,0,0,1,0,0,0,0
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,...,1,0,0,0,0,0,0,0,0,0
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,...,0,0,0,1,0,0,0,0,0,0
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,...,0,0,0,0,0,1,0,0,0,0
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,...,0,0,0,0,1,0,0,0,0,0
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,...,0,0,0,1,0,0,0,0,0,0
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,...,0,0,0,0,0,0,0,1,0,0
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,...,0,0,0,1,0,0,0,0,0,0
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,...,0,0,0,0,0,0,0,1,0,0
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,...,0,0,0,1,0,0,0,0,0,0
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,...,0,0,0,0,0,0,0,1,0,0
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,...,0,0,0,0,0,0,0,1,0,0
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,...,0,0,0,0,0,0,0,0,1,0
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,...,0,0,0,0,0,0,0,1,0,0
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,...,0,0,0,1,0,0,0,0,0,0
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,...,0,0,0,0,0,0,1,0,0,0
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,...,0,0,0,0,0,0,1,0,0,0
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,...,0,0,0,0,0,0,0,0,1,0
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,...,0,0,0,0,0,0,0,0,1,0
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,...,0,0,0,0,0,0,0,0,1,0
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,...,0,0,0,0,0,0,0,1,0,0
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,...,0,0,0,0,0,0,1,0,0,0
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,...,0,0,0,0,0,0,1,0,0,0
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,...,0,0,0,0,0,0,0,0,1,0
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,...,0,0,0,0,0,0,0,0,1,0
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,...,0,0,0,1,0,0,0,0,0,0
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,...,0,0,0,0,0,0,0,1,0,0
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,...,0,0,0,0,0,0,0,0,1,0
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,52228,0.0,2013-01-27,Dbfpe,265,DBFPE,38.504640,-1.016990e+01,Shule Ya Msingi Mayaka,0,...,0,0,0,0,0,1,0,0,0,0
74221,70038,5.0,2013-03-29,Ces (gmbh),1322,DWE,37.261731,-3.235687e+00,Kwa Leonard Soka,0,...,0,0,0,0,0,0,1,0,0,0
74222,25901,50.0,2013-01-22,Lga,640,LGA,39.297410,-1.092504e+01,Tangini,0,...,0,0,0,0,0,0,0,0,1,0
74223,21131,0.0,2011-04-03,Government Of Tanzania,0,DWE,33.918953,-9.298466e+00,Ndubi,0,...,0,0,0,0,0,0,0,0,1,0
74224,26580,0.0,2011-04-20,Po,574,Po,37.070462,-6.575076e+00,Mwanji,0,...,0,0,0,0,0,0,0,1,0,0
74225,66059,0.0,2013-02-02,Fin Water,331,FIN WATER,38.761961,-1.091314e+01,Mkwajuni,0,...,0,0,0,1,0,0,0,0,0,0
74226,32944,0.0,2012-10-24,World Vision,0,World vision,32.243937,-3.311621e+00,Umoja,0,...,0,0,0,0,0,0,0,1,0,0
74227,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,0,0,0,0,0,0,0,1,0,0
74228,8471,50.0,2011-02-20,Private,78,Private,39.254272,-7.060921e+00,Mkopi,0,...,0,0,0,1,0,0,0,0,0,0
74229,19620,0.0,2013-01-03,Government Of Tanzania,836,Government,35.227320,-1.103905e+01,Kituo Ch Afya,0,...,0,0,0,0,0,0,0,0,1,0
74230,74162,0.0,2013-03-19,Tcrs,1651,TCRS,37.962243,-4.494348e+00,Kwa Andrew,0,...,0,0,0,0,0,0,0,0,1,0
74231,37994,0.0,2012-10-26,Hesawa,0,DWE,0.000000,-2.000000e-08,Kwa Masilili,0,...,0,0,0,0,0,0,0,1,0,0
74232,71151,0.0,2013-03-25,Kkkt,1393,KKKT,36.930169,-3.255077e+00,Tankini,0,...,0,0,0,1,0,0,0,0,0,0
74233,45017,1000.0,2011-03-05,Kkkt,1729,Commu,34.302104,-9.455737e+00,none,0,...,0,0,0,0,0,0,0,0,1,0
74234,12592,0.0,2011-03-27,Kirde,0,DWE,35.840727,-4.633272e+00,Kwa Mrangi,0,...,0,0,0,0,0,0,0,0,1,0
74235,58693,0.0,2013-01-25,Rwssp,0,DWE,32.442886,-3.644662e+00,Busangi,0,...,0,0,0,0,0,0,0,1,0,0
74236,57539,0.0,2011-03-18,Amref,-7,AMREF,39.140091,-7.477423e+00,Nyamalonda,0,...,0,0,0,0,0,0,0,1,0,0
74237,71252,500.0,2013-02-10,Tasaf,1241,TASAF,30.114667,-4.162845e+00,Pentecoste Church,0,...,0,0,0,1,0,0,0,0,0,0
74238,7869,3000.0,2011-03-11,Kkkt,2046,Commu,34.345525,-9.547077e+00,none,0,...,0,0,0,0,0,0,0,0,1,0
74239,57316,0.0,2011-03-11,Devon Aid Korogwe,347,Local technician,38.613415,-4.815222e+00,Jahiya,0,...,0,0,0,0,0,0,0,0,1,0
74240,59757,0.0,2013-02-24,Villagers,1291,Villagers,35.345384,-9.831170e+00,Kwa Reonard,0,...,0,0,0,0,0,0,1,0,0,0
74241,64579,0.0,2012-10-26,Dwsp,0,DWE,0.000000,-2.000000e-08,Iguna,0,...,0,0,0,0,0,0,0,1,0,0
74242,57731,600.0,2013-01-27,Isf,808,DWE,29.740224,-4.882705e+00,Hongera,0,...,0,0,0,0,0,0,1,0,0,0
74243,65541,0.0,2013-02-04,Oxfarm,1641,OXFARM,29.768139,-4.480618e+00,Mwandami,0,...,0,0,0,0,0,0,0,0,1,0
74244,68174,0.0,2012-11-07,Netherlands,0,DWE,34.096878,-3.079689e+00,Ikanayugu,0,...,0,0,0,0,0,0,0,1,0,0
74245,39307,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841e+00,Kwambwezi,0,...,0,0,0,0,0,0,1,0,0,0
74246,18990,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428e+00,Bonde La Mkondoa,0,...,0,0,0,0,0,0,0,1,0,0
74247,28749,0.0,2013-03-04,Government Of Tanzania,1476,DWE,34.739804,-4.585587e+00,Bwawani,0,...,1,0,0,0,0,0,0,0,0,0
74248,33492,0.0,2013-02-18,Germany,998,DWE,35.432732,-1.058416e+01,Kwa John,0,...,0,0,0,0,0,0,1,0,0,0
74249,68707,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-1.122601e+01,Kwa Mzee Chagala,0,...,0,0,0,0,0,0,0,0,1,0

In [554]:
part_feature = ['extraction_type_class','management','management_group','payment','payment_type','water_quality','quality_group',
                'quantity','quantity_group','extraction_type','extraction_type_group','scheme_management','recorded_by']
for feature in part_feature:
    features = pd.DataFrame()
    features= pd.get_dummies(data[feature],prefix=feature)
    data = pd.concat([data,features],axis=1)
    data.drop(feature,axis=1)

In [555]:
data.shape

(74250, 176)

In [556]:
Counter(data['installer'])

Counter({'Roman': 119,
         'GRUMETI': 50,
         'World vision': 517,
         'UNICEF': 285,
         'Artisan': 169,
         'DWE': 26283,
         'DWSP': 239,
         'Water Aid': 57,
         'Private': 183,
         'DANIDA': 1305,
         'Lawatefuka water sup': 229,
         'WEDECO': 496,
         'Danid': 96,
         'TWE': 138,
         'ISF': 168,
         'Kilolo Star': 2,
         'District council': 490,
         'Water': 84,
         'WU': 377,
         'Not known': 21,
         'Central government': 764,
         'CEFA': 101,
         'Commu': 1347,
         'Accra': 39,
         'World Vision': 326,
         'LGA': 501,
         'MUWSA': 132,
         'KKKT _ Konde and DWE': 209,
         'Government': 2282,
         'Olgilai village community': 16,
         'KKKT': 1120,
         'RWE': 1498,
         'Adra /Community': 62,
         'SEMA': 311,
         'SHIPO': 183,
         'HESAWA': 679,
         'ACRA': 346,
         'Community': 687,
         'IFAD': 30,
         'Sengerema Water Department': 258,
         'HE': 153,
         'ISF and TACARE': 1,
         'Kokeni': 37,
         'DA': 111,
         'Adra': 106,
         'ALLYS': 1,
         'AICT': 108,
         'KIUMA': 39,
         'CES': 765,
         'District Counci': 14,
         'Ruthe': 16,
         'Adra/Community': 73,
         'Tulawaka Gold Mine': 9,
         'KKT C': 6,
         'Hesawa': 1070,
         'Water board': 102,
         'LOCAL CONTRACT': 38,
         'WFP': 18,
         'LIPS': 4,
         'TASAF': 504,
         'World': 153,
         '0': 980,
         'SW': 3,
         'Shipo': 108,
         'Fini water': 157,
         'Kanisa': 7,
         'OXFARM': 121,
         'VILLAGE COUNCIL Orpha': 7,
         'Villagers': 262,
         'Idara ya maji': 254,
         'FPCT': 16,
         'WVT': 206,
         'Ir': 147,
         'DANID': 690,
         'Angli': 113,
         'secondary school': 5,
         'Amref': 140,
         'JBG': 49,
         'DADIS': 1,
         'International Aid Services': 1,
         'RW': 21,
         'Dmdd': 356,
         'TCRS': 887,
         'RC Church': 92,
         'WATER AID': 120,
         'JICA': 139,
         'Gwasco L': 33,
         'AF': 6,
         'AMREF': 398,
         'wananchi': 151,
         'FW': 214,
         'Central Government': 135,
         'MWE &': 57,
         'Gove': 276,
         'RC CHURCH': 162,
         'TDFT': 51,
         'RWE/DWE': 64,
         'Central govt': 175,
         'World Bank': 123,
         'TWESA': 395,
         'Norad': 190,
         'Hans': 32,
         'FinW': 267,
         'FIN WATER': 82,
         'OXFAM': 288,
         'Plan Internationa': 61,
         'District Council': 663,
         'RWEDWE': 1,
         'Fini Water': 188,
         'ANGLI': 7,
         'CDT': 1,
         'North': 2,
         'Oikos E .Africa': 92,
         'SHAWASA': 56,
         'UN': 38,
         'NORAD': 260,
         'Save the rain': 9,
         'John gemuta co': 1,
         'TLC': 72,
         'RC Churc': 17,
         'Plan Int': 22,
         'Phase': 14,
         'LVIA': 71,
         'Rhobi': 35,
         'Makonde water population': 21,
         'RWE/ Community': 8,
         'Is': 187,
         'KILI WATER': 45,
         'RDDC': 1,
         'FINN WATER': 41,
         'FINI WATER': 120,
         'DHV': 66,
         'Kamama': 1,
         'DDCA': 154,
         'Victoria company': 5,
         'RWSSP': 180,
         'Ce': 28,
         'KYASHA ENTERPR': 26,
         'ERETO': 33,
         'REDESO': 8,
         'Villa': 79,
         'Priva': 78,
         'KUWAIT': 66,
         'Mw': 18,
         'Magadini-Makiwaru wa': 226,
         'Dr. Matomola': 10,
         'Af': 30,
         'RCchurch/CEFA': 27,
         'Tardo': 154,
         'GOVERNMENT': 85,
         'Individuals': 27,
         'Chamavita': 85,
         'GEN': 72,
         'Missi': 101,
         'Safari Roya': 1,
         'DAWASCO': 87,
         'Gover': 483,
         'Mission': 167,
         'DWE/': 8,
         'Halmashauri ya wilaya sikonge': 132,
         'Ki': 127,
         'Rhoda': 11,
         'HAPA SINGIDA': 39,
         'Consulting Engineer': 147,
         'Karugendo': 13,
         'Co': 73,
         'Marafip': 11,
         'COSMOS ENG LTD': 10,
         'World banks': 3,
         'Tanz': 23,
         'Handeni Trunk Main(': 208,
         'SIMBA CO': 8,
         'Local technician': 35,
         'Village': 10,
         'Centr': 195,
         'CONS': 35,
         'DW': 308,
         'DCT': 8,
         'IRC': 2,
         'District water department': 108,
         'Sabodo': 24,
         'MLADE': 53,
         'I.E.C': 8,
         'LWI': 98,
         'Kiliflora': 14,
         'ICS': 34,
         'T. N. karugendo': 5,
         'DED': 126,
         'Kuwait': 187,
         'ADP': 23,
         'JUIN CO': 32,
         'BILILA': 5,
         'TPP': 3,
         'GOVER': 170,
         'CIPRO/Government': 26,
         'MWE': 198,
         'MTUWASA': 28,
         'Unisef': 119,
         'REGIONAL WATER ENGINEER ARUSHA': 11,
         'IDARA': 10,
         'Wizara ya maji': 127,
         'Tasaf and Lga': 1,
         'JAICA': 184,
         'KKKT-Dioces ya Pare': 12,
         'Onesm': 1,
         'Te': 1,
         'MTN': 81,
         'HESAWS': 1,
         'Islamic': 21,
         'Local': 55,
         'KTA C': 7,
         'RC': 219,
         'Killflora /Community': 10,
         'Distri': 224,
         'Maji block': 7,
         'CALTAZ KAHAMA': 1,
         'GOVERNME': 3,
         'Omar Ally': 1,
         'HAM': 15,
         'QUWKWIN': 21,
         'ADRA': 71,
         'DO': 11,
         'DH': 246,
         'RC Ch': 69,
         'SAXON BUILDING CONTRACTOR': 8,
         'Bokera W': 2,
         'Bulyahunlu Gold Mine': 8,
         'MBIUWASA': 41,
         'ADRA /Government': 7,
         'The Isla': 17,
         'Rotary club': 18,
         'YELL LTD': 2,
         'Care international': 27,
         'KIMKUM': 8,
         'Tanesco': 3,
         'CJEJOW CONSTRUCTION': 40,
         'Victoria': 9,
         'TLTC': 11,
         'Wachina': 81,
         'WE': 6,
         'HSW': 118,
         'Communit': 68,
         'Kibaha Town Council': 4,
         'Dr. Matobola': 6,
         'Go': 112,
         'DWR': 16,
         'Huches': 1,
         'WATERAID': 40,
         'Maswi company': 23,
         'Kiliwater': 271,
         'TA': 26,
         'wanan': 62,
         'MEM': 7,
         'Region water Department': 90,
         'Jeica': 14,
         'Ndanda missions': 26,
         'District Water Department': 94,
         'MSF/TACARE': 13,
         'Fathe': 29,
         'DARDO': 9,
         'Wa': 82,
         'MSIKIT': 4,
         'Regional Water': 16,
         'D': 11,
         'VILLAGE COUNCIL': 48,
         'RDC': 73,
         'TLC/John Majala': 2,
         'Kilwa company': 12,
         'Local  technician': 60,
         'TASSAF': 79,
         'VWC': 118,
         'PIDP': 13,
         'TAN PLANT LTD': 27,
         'Japan Government': 2,
         'Kata': 2,
         'GTZ': 73,
         'ISF/Government': 20,
         'KUWASA': 49,
         'Hydrotec': 28,
         'Pr': 61,
         'Ch': 41,
         'Jaica': 122,
         'Taboma/Community': 1,
         'P': 20,
         'Ubung': 10,
         'Chur': 27,
         'BESADA': 29,
         'Action Contre La Faim': 11,
         'Wanjoda': 7,
         'CBHCC': 54,
         'HW/RC': 30,
         'Sumbaw': 20,
         'CCEC': 40,
         'Nice': 13,
         'CCT': 10,
         'World Vission': 14,
         'Inter': 18,
         'DMMD': 1,
         'WORLD BANK': 67,
         'AQUA BLUES ANGELS': 1,
         'MACK DONALD CONTRACTOR': 8,
         'Water Aid /sema': 56,
         'Henure Dema': 2,
         'Kirdep': 8,
         'ADRA/Government': 3,
         'Kilwater': 33,
         'Da': 287,
         'Villi': 1,
         'KOYI': 2,
         'AD': 17,
         'Arab community': 1,
         'District water depar': 56,
         'HOLLAND': 37,
         'RC church/Central Gover': 18,
         'Active MKM': 33,
         'GEOTAN': 37,
         'LENCH': 7,
         'NCAA': 69,
         'CHINA HENAN CONSTUCTION': 1,
         'Kaembe': 3,
         'Ma': 18,
         'FinWater': 37,
         'Kuamu': 24,
         'Adra/ Community': 21,
         'Locall technician': 3,
         'UKILIG': 17,
         'Mbunge': 27,
         'The desk and chair foundat': 40,
         'DUWAS': 13,
         'Diwani': 2,
         'Biore': 1,
         'Water aid /sema': 6,
         'KKKT CHURCH': 88,
         'EA': 5,
         'Halmashauri ya manispa tabora': 15,
         'ML appro': 14,
         'SHY BUILDERS': 44,
         'Finwater': 72,
         'JIKA': 28,
         'Orien': 24,
         'DMDD': 120,
         'DWE}': 20,
         'CDTF': 60,
         'KAEMP': 32,
         'TUWASA': 41,
         'MARAFIP': 28,
         'MDRDP': 104,
         'Jeshi la wokovu': 3,
         'kuwait': 7,
         'MBOMA': 7,
         'Grobal resource alliance': 18,
         'Village Council': 68,
         'Shamte Said': 1,
         'AUWASA': 10,
         'WSDP': 19,
         'COUN': 8,
         'KIDP': 45,
         'Mombo urban water s': 5,
         'TRIDEP': 7,
         'Wananchi': 44,
         'Martha Emanuel': 2,
         'St': 66,
         'GIDA contractor': 5,
         'WD and ID': 30,
         'Padep': 5,
         'Po': 39,
         'Village Counil': 6,
         'MINISTRY OF WATER': 17,
         'Ga': 54,
         'K': 2,
         'Swiss If': 35,
         'Miziriol': 53,
         'Yasini Selemani': 1,
         'DBSPE': 5,
         'European Union': 16,
         'H': 102,
         'TPP TRUSTMOSHI': 19,
         'Atisan': 5,
         'Jika': 4,
         'ISF/TACARE': 18,
         'Oikos E.Africa': 4,
         'Hydom Luthelani': 3,
         'Kalumbwa': 11,
         'ILCT': 27,
         'MS': 6,
         'RUVUMA BASIN': 3,
         'Gold star': 6,
         'Mi': 27,
         'Mzungu Paul': 9,
         'Kanisa katoliki': 5,
         'Caltas': 4,
         'RED CROSS': 40,
         'World bank': 12,
         'Losaa-Kia water supp': 73,
         'Jica': 33,
         'PET': 32,
         'Finland Government': 23,
         'GAICA': 5,
         'Institution': 10,
         'TCRS/TLC': 4,
         'Loliondo Parish': 4,
         'GACHUMA CONSTRUCTION': 1,
         'Diocese of Geita': 5,
         'Villages': 1,
         'MSABI': 2,
         'Total landcare': 8,
         'VICTORIA DRILL CO': 5,
         'U.S.A': 4,
         'VTECOS': 43,
         'COW': 1,
         'Vill': 14,
         'Contr': 9,
         'Wadeco': 1,
         'KIM KIM CONSTRUCTION': 24,
         'Msabi': 36,
         'VC': 1,
         'CMSR': 34,
         'Ko': 2,
         'Roman Catholic Rulenge Diocese': 10,
         'Shule': 9,
         'W': 16,
         'inkinda': 1,
         'Africa Amini Alama': 2,
         'Consultant': 15,
         'L': 3,
         'Moroil': 10,
         'Sekei village community': 25,
         'US Embassy': 16,
         'PIT COOPERATION  LTD': 12,
         'Do': 41,
         'world': 5,
         'Government /TCRS': 1,
         'UNHCR': 14,
         'DESK C': 7,
         'Dr.Matomola': 2,
         'FOLAC': 3,
         'Village govt': 9,
         'BSF': 40,
         'Roman Cathoric Same': 9,
         'RWE/Community': 8,
         'Mileniam project': 31,
         'ACTIVE TANK CO': 11,
         'Ncaa': 6,
         'Africa Islamic Agency Tanzania': 3,
         'Max Mbise': 1,
         'DADS': 19,
         'Institutional': 1,
         'SOWASA': 26,
         'CCPK': 1,
         'AUSTRALIA': 4,
         'not known': 26,
         'Kalago enterprises Co.Ltd': 11,
         'Roman Catholic': 8,
         'NANRA contractor': 7,
         'WORLD VISION': 23,
         'No': 10,
         'ADP Busangi': 18,
         'TSRC': 1,
         'SOLIDAME': 55,
         'Barry A. Murphy': 1,
         'Tanzania Government': 37,
         'WILLIAMSON DIAMOND LTD': 11,
         'TAG': 12,
         'The I': 17,
         'Total Landcare': 1,
         'CENTRAL GOVERNMENT': 15,
         'Arabs Community': 2,
         'Secondary school': 1,
         'Water Aid/Sema': 15,
         'Jiks': 1,
         'Konoike': 10,
         'ABASIA': 34,
         'LAMP': 13,
         'SINGIDA YETU': 22,
         'RWSP': 18,
         'MDALA Contractor': 8,
         'Netherlands': 3,
         'DWT': 2,
         'TCRS /CARE': 6,
         'Makonde': 9,
         'Japan': 9,
         'Milenium': 5,
         'Goldstar': 14,
         'District COUNCIL': 8,
         'MUWASA': 43,
         'Green': 2,
         'Kigoma municipal': 12,
         'KINAPA': 5,
         'CHINA HENAN CONTRACTOR': 16,
         'Musa': 7,
         'TANAPA': 37,
         'Ministry of water engineer': 11,
         'EFG': 22,
         'MASWI': 6,
         'Kyariga': 3,
         'Roman Cathoric -Kilomeni': 10,
         'Mbozi Secondary School': 1,
         'TASAF/DMDD': 20,
         'MWS': 8,
         'Roman catholic': 5,
         'Shekhe': 1,
         'Rished': 6,
         'KONOIKE': 8,
         'Pata': 6,
         'TAHEA': 19,
         'Luthe': 8,
         'Kalta': 42,
         'Pentecost church': 1,
         'Amboni Plantation': 5,
         'Municipal': 2,
         'Sekondari': 1,
         'Kalitasi': 32,
         'HOTELS AND LOGGS TZ LTD': 1,
         'DISTRICT COUNCIL': 20,
         'Germany': 7,
         'Orphanage': 1,
         'WWF': 27,
         'W.B': 2,
         'IDYDC': 26,
         'SIA Ltd': 18,
         'WINAM  CONSTRUCTION': 1,
         'RIDEP': 28,
         'NORA': 25,
         'SCHOOL': 2,
         'Village community': 17,
         'British': 1,
         'Msuba': 1,
         'Villaers': 2,
         'TLC/Thimotheo Masunga': 1,
         'WB': 44,
         'Council': 9,
         'DAK': 12,
         'COCANE': 33,
         'WINAMU CO': 1,
         'Ubalozi wa Marekani': 10,
         'Conce': 12,
         'BGM': 35,
         'DMK': 2,
         'Mviwa': 16,
         'KA': 55,
         'MGM': 5,
         'AIMGOLD': 11,
         'YEBE CHIKOMESH': 3,
         'Omari Mzee': 1,
         'Petro Patrice': 1,
         'Camartec': 1,
         'Total land care': 24,
         'Wasso companies': 5,
         'DASP': 2,
         'Islamic Agency Tanzania': 2,
         'Tanz Egypt technical coopera': 3,
         'Village Govt': 1,
         'local technician': 2,
         'TAWASA': 28,
         'WATER  AID': 13,
         'AAR': 5,
         'MSF': 17,
         'Di': 1,
         'Mackd': 19,
         'MAMAD': 16,
         'PADEP': 35,
         'Fabia': 1,
         'CONCERN': 28,
         'ITALI': 2,
         'Water aid/sema': 3,
         'Save the rain USA': 29,
         'Plan Tanzania': 3,
         'Roman Church': 18,
         'Singasinga': 3,
         'RC/Mission': 7,
         'In': 3,
         'V': 1,
         'Korogwe water works': 30,
         'PCI': 8,
         'Atlas': 1,
         'DWE /TASSAF': 1,
         'Local te': 68,
         'World Division': 2,
         'Gwaseco': 12,
         'Kambi Migoko': 1,
         'AI': 16,
         'SAUWASA': 7,
         'Nyakilanganyi': 1,
         'DEE': 4,
         'MANYARA CONSTRUCTION': 7,
         'Rotte': 3,
         'KMCL': 13,
         'LINDALA CO': 4,
         'Government /Community': 1,
         'CCPS': 2,
         'SI': 45,
         'Rundu man': 8,
         'Water Aid/sema': 17,
         'Naishu construction co. ltd': 20,
         'WOULD BANK': 18,
         'Mark': 2,
         'Cosmo': 30,
         'Halmashauri': 29,
         'Concern /government': 9,
         'Quick win project': 4,
         'Mh Kapuya': 2,
         'Halmashauri ya wilaya': 4,
         'Edward': 4,
         'COMMU': 6,
         'Baric': 8,
         'Consuting Engineer': 26,
         'JANDU PLUMBER CO': 53,
         'FiNI WATER': 4,
         'CPRO': 6,
         'Getekwe': 1,
         'Jicks': 25,
         'Wahidi': 1,
         'Mohamed Ally': 1,
         'ASDP': 3,
         'CITIZEN ENGINE': 19,
         'KADP': 31,
         'Dar es salaam Technician': 1,
         'Halmashauli': 4,
         'ACORD': 4,
         'MA': 24,
         'Water  Aid/Sema': 7,
         'RC church/CEFA': 1,
         'Wedeco': 2,
         'DWE/Ubalozi wa Marekani': 1,
         'VIFAFI': 30,
         'Kwasenenge Group': 1,
         'Cosmos Engineering': 15,
         'OLDONYOLENGAI': 4,
         'NYAKILANGANI CO': 25,
         'Village Community': 19,
         'MINJINGU': 3,
         'EL': 9,
         'Songa': 18,
         'Consultant and DWE': 6,
         'AC': 5,
         'Gain': 13,
         'DASIP': 6,
         'TANROAD': 4,
         'Tasaf': 19,
         'Wasso': 5,
         'Teonas Wambura': 1,
         'Mgaya Masese': 1,
         'TUKWALE ENTERP': 1,
         'Sao': 15,
         'MWAKI CONTRACTOR': 3,
         'VIEN CONSTRUCTION': 2,
         'mwita kichere': 1,
         'DADS/village community': 5,
         'Africare': 4,
         'Mosque': 14,
         'Chiko': 8,
         'central government': 19,
         'VITECOS': 3,
         'IN': 1,
         'Msikiti': 13,
         'Word Bank': 2,
         'Kwamdulu estate': 1,
         'SEMA Consultant': 1,
         'Concern': 22,
         'Belgiam Government': 10,
         'Wanan': 6,
         'Exaud Msambwa': 13,
         'Niger': 2,
         'MWANZA': 1,
         'SONGAS': 10,
         'MINISTRYOF WATER': 6,
         'COMMUNITY': 3,
         'Zaburi and neighbors': 1,
         'NDM': 1,
         'Killflora/ Community': 15,
         'PART': 7,
         'secondary': 18,
         "lion's club": 1,
         'lutheran church': 10,
         'Mileniam': 10,
         'UYOGE': 3,
         'Christina Magoge': 1,
         'Canada na Tanzania': 15,
         'FRANKFURT': 1,
         'GOVERM': 3,
         'Kuji foundation': 1,
         'Mamvua Kakungu': 1,
         'Rusumo Game reserve': 1,
         'MTUWASA and Community': 4,
         'ACT MARA': 1,
         'UMOJA DRILLING': 4,
         'KkKT': 12,
         'SDA': 20,
         'Mzinga A': 11,
         'RE': 11,
         'LOOCIP': 1,
         'SUA': 1,
         'RUNDAGA': 5,
         'RWE /Community': 17,
         'Wo': 28,
         'Happy watoto foundation': 37,
         'GDP': 1,
         'ViLLAGE COUNCIL': 1,
         'MBULU DISTRICT COUNCIL': 1,
         'Maliasili': 1,
         'Roman Ca': 5,
         'NZILA': 1,
         'stansilaus': 2,
         'AFRICAN DEVELOPMENT FOUNDATION': 9,
         'FPTC': 2,
         'KARUMBA BIULDING COMPANY LTD': 2,
         'Kalugendo': 2,
         'Village Government': 9,
         'Tabraki': 5,
         'MASWI DRILLING': 4,
         'Ikela Wa': 10,
         'Shallow well': 1,
         'WEDECO/WESSONS': 8,
         'CIPRO/CARE/TCRS': 7,
         'Wasso contractors': 5,
         'villagers': 14,
         'Mwanga town water authority': 5,
         'Jumanne Siabo': 1,
         'Mama Kalage': 1,
         'Hindu': 3,
         'Rural': 3,
         'TANAP': 7,
         'Makonde water supply': 4,
         'villigers': 1,
         'Bingo foundation Germany': 1,
         'Ilwilo community': 1,
         'St ph': 5,
         'WDECO': 1,
         'LIVI': 16,
         'Pet Corporation Ltd': 14,
         'DWE & LWI': 1,
         'LC': 1,
         'KKKT Leguruki': 1,
         'HIAP': 7,
         'Matyenye': 2,
         'DIMON': 1,
         'Italy government': 4,
         'MASWI DRILL': 5,
         'WVC': 3,
         'TACRI': 1,
         'Hasnein Murij': 1,
         'SIMBA LODGE': 1,
         'Faudh Tamimu': 2,
         'Free Pentecoste Church of Tanz': 6,
         'Summit for water/Community': 11,
         'Sanje Wa': 7,
         'Makundya': 2,
         'Individual': 3,
         'OLA': 5,
         'RC C': 16,
         'TREDEP': 32,
         'Consultant Engineer': 14,
         'AQUA WEL': 1,
         'Cental Government': 6,
         'Nyanza road': 1,
         'Kizenga': 1,
         'KKT': 41,
         'HAPA': 10,
         'Oikos E. Africa': 7,
         'Ramadhani Nyambizi': 1,
         'Mdala Contractor': 2,
         'DENISH': 2,
         'Mkuyu': 20,
         'GOVERN': 32,
         'GACHUMA GINERY': 4,
         'Resolute': 2,
         'Morrov': 1,
         'Serikali ya kijiji': 12,
         'Counc': 8,
         'Igolola community': 1,
         'S': 2,

In [557]:
data

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,scheme_management_Parastatal,scheme_management_Private operator,scheme_management_SWC,scheme_management_Trust,scheme_management_VWC,scheme_management_WUA,scheme_management_WUG,scheme_management_Water Board,scheme_management_Water authority,recorded_by_GeoData Consultants Ltd
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,...,0,0,0,0,1,0,0,0,0,1
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,...,0,0,0,0,0,0,0,0,0,1
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,...,0,0,0,0,1,0,0,0,0,1
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,...,0,0,0,0,1,0,0,0,0,1
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,...,0,0,0,0,1,0,0,0,0,1
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,...,0,0,0,0,1,0,0,0,0,1
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,...,0,0,0,0,1,0,0,0,0,1
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,...,0,0,0,0,1,0,0,0,0,1
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,...,0,0,0,0,1,0,0,0,0,1
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,...,0,0,0,0,1,0,0,0,0,1
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,...,0,1,0,0,0,0,0,0,0,1
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,...,0,0,0,0,0,0,1,0,0,1
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,...,0,0,0,0,0,0,1,0,0,1
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,...,0,0,0,0,0,0,0,1,0,1
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,...,0,0,0,0,0,0,1,0,0,1
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,...,0,0,0,0,1,0,0,0,0,1
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,...,0,0,0,0,0,1,0,0,0,1
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,...,0,0,0,0,0,1,0,0,0,1
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,...,0,0,0,0,1,0,0,0,0,1
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,...,0,0,0,0,1,0,0,0,0,1
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,...,0,0,0,0,1,0,0,0,0,1
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,...,0,0,0,0,0,0,1,0,0,1
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,...,0,0,0,0,0,1,0,0,0,1
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,...,0,0,0,0,0,0,0,0,1,1
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,...,0,0,0,0,1,0,0,0,0,1
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,...,0,0,0,0,1,0,0,0,0,1
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,...,0,0,0,0,1,0,0,0,0,1
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,...,0,0,0,0,1,0,0,0,0,1
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,...,0,0,0,0,0,0,0,0,0,1
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,52228,0.0,2013-01-27,Dbfpe,265,DBFPE,38.504640,-1.016990e+01,Shule Ya Msingi Mayaka,0,...,0,0,0,0,1,0,0,0,0,1
74221,70038,5.0,2013-03-29,Ces (gmbh),1322,DWE,37.261731,-3.235687e+00,Kwa Leonard Soka,0,...,0,0,0,0,0,0,0,1,0,1
74222,25901,50.0,2013-01-22,Lga,640,LGA,39.297410,-1.092504e+01,Tangini,0,...,0,0,0,0,0,0,0,0,0,1
74223,21131,0.0,2011-04-03,Government Of Tanzania,0,DWE,33.918953,-9.298466e+00,Ndubi,0,...,1,0,0,0,0,0,0,0,0,1
74224,26580,0.0,2011-04-20,Po,574,Po,37.070462,-6.575076e+00,Mwanji,0,...,0,0,0,0,1,0,0,0,0,1
74225,66059,0.0,2013-02-02,Fin Water,331,FIN WATER,38.761961,-1.091314e+01,Mkwajuni,0,...,0,0,0,0,1,0,0,0,0,1
74226,32944,0.0,2012-10-24,World Vision,0,World vision,32.243937,-3.311621e+00,Umoja,0,...,0,0,0,0,0,0,1,0,0,1
74227,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,0,0,0,0,1,0,0,0,0,1
74228,8471,50.0,2011-02-20,Private,78,Private,39.254272,-7.060921e+00,Mkopi,0,...,0,1,0,0,0,0,0,0,0,1
74229,19620,0.0,2013-01-03,Government Of Tanzania,836,Government,35.227320,-1.103905e+01,Kituo Ch Afya,0,...,0,0,0,0,1,0,0,0,0,1
74230,74162,0.0,2013-03-19,Tcrs,1651,TCRS,37.962243,-4.494348e+00,Kwa Andrew,0,...,0,0,0,0,0,0,0,0,1,1
74231,37994,0.0,2012-10-26,Hesawa,0,DWE,0.000000,-2.000000e-08,Kwa Masilili,0,...,0,0,0,0,1,0,0,0,0,1
74232,71151,0.0,2013-03-25,Kkkt,1393,KKKT,36.930169,-3.255077e+00,Tankini,0,...,0,0,0,0,1,0,0,0,0,1
74233,45017,1000.0,2011-03-05,Kkkt,1729,Commu,34.302104,-9.455737e+00,none,0,...,0,0,0,0,1,0,0,0,0,1
74234,12592,0.0,2011-03-27,Kirde,0,DWE,35.840727,-4.633272e+00,Kwa Mrangi,0,...,0,0,0,0,1,0,0,0,0,1
74235,58693,0.0,2013-01-25,Rwssp,0,DWE,32.442886,-3.644662e+00,Busangi,0,...,0,0,0,0,1,0,0,0,0,1
74236,57539,0.0,2011-03-18,Amref,-7,AMREF,39.140091,-7.477423e+00,Nyamalonda,0,...,0,0,0,0,1,0,0,0,0,1
74237,71252,500.0,2013-02-10,Tasaf,1241,TASAF,30.114667,-4.162845e+00,Pentecoste Church,0,...,0,0,0,0,0,0,0,0,1,1
74238,7869,3000.0,2011-03-11,Kkkt,2046,Commu,34.345525,-9.547077e+00,none,0,...,0,0,0,0,1,0,0,0,0,1
74239,57316,0.0,2011-03-11,Devon Aid Korogwe,347,Local technician,38.613415,-4.815222e+00,Jahiya,0,...,0,0,0,0,0,0,0,0,0,1
74240,59757,0.0,2013-02-24,Villagers,1291,Villagers,35.345384,-9.831170e+00,Kwa Reonard,0,...,0,0,0,0,1,0,0,0,0,1
74241,64579,0.0,2012-10-26,Dwsp,0,DWE,0.000000,-2.000000e-08,Iguna,0,...,0,0,0,0,0,0,1,0,0,1
74242,57731,600.0,2013-01-27,Isf,808,DWE,29.740224,-4.882705e+00,Hongera,0,...,0,0,0,0,0,0,1,0,0,1
74243,65541,0.0,2013-02-04,Oxfarm,1641,OXFARM,29.768139,-4.480618e+00,Mwandami,0,...,0,0,0,0,0,0,0,0,1,1
74244,68174,0.0,2012-11-07,Netherlands,0,DWE,34.096878,-3.079689e+00,Ikanayugu,0,...,0,0,0,0,0,0,1,0,0,1
74245,39307,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841e+00,Kwambwezi,0,...,0,0,0,0,1,0,0,0,0,1
74246,18990,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428e+00,Bonde La Mkondoa,0,...,0,0,0,0,1,0,0,0,0,1
74247,28749,0.0,2013-03-04,Government Of Tanzania,1476,DWE,34.739804,-4.585587e+00,Bwawani,0,...,0,0,0,0,1,0,0,0,0,1
74248,33492,0.0,2013-02-18,Germany,998,DWE,35.432732,-1.058416e+01,Kwa John,0,...,0,0,0,0,1,0,0,0,0,1
74249,68707,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-1.122601e+01,Kwa Mzee Chagala,0,...,0,0,0,0,1,0,0,0,0,1

In [558]:
drop_feature = ['date_recorded','funder','installer','wpt_name','basin','subvillage','region','lga','ward']
bool_feature = ['permit','public_meeting']
data['permit']= data['permit'].astype('int')
data['public_meeting']= data['public_meeting'].astype('int')

data.drop(drop_feature,axis=1)

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,public_meeting,...,scheme_management_Parastatal,scheme_management_Private operator,scheme_management_SWC,scheme_management_Trust,scheme_management_VWC,scheme_management_WUA,scheme_management_WUG,scheme_management_Water Board,scheme_management_Water authority,recorded_by_GeoData Consultants Ltd
0,69572,6000.0,1390,34.938093,-9.856322e+00,0,11,5,109,1,...,0,0,0,0,1,0,0,0,0,1
1,8776,0.0,1399,34.698766,-2.147466e+00,0,20,2,280,1,...,0,0,0,0,0,0,0,0,0,1
2,34310,25.0,686,37.460664,-3.821329e+00,0,21,4,250,1,...,0,0,0,0,1,0,0,0,0,1
3,67743,0.0,263,38.486161,-1.115530e+01,0,90,63,58,1,...,0,0,0,0,1,0,0,0,0,1
4,19728,0.0,0,31.130847,-1.825359e+00,0,18,1,0,1,...,0,0,0,0,1,0,0,0,0,1
5,9944,20.0,0,39.172796,-4.765587e+00,0,4,8,1,1,...,0,0,0,0,1,0,0,0,0,1
6,19816,0.0,0,33.362410,-3.766365e+00,0,17,3,0,1,...,0,0,0,0,1,0,0,0,0,1
7,54551,0.0,0,32.620617,-4.226198e+00,0,17,3,0,1,...,0,0,0,0,1,0,0,0,0,1
8,53934,0.0,0,32.711100,-5.146712e+00,0,14,6,0,1,...,0,0,0,0,1,0,0,0,0,1
9,46144,0.0,0,30.626991,-1.257051e+00,0,18,1,0,1,...,0,0,0,0,1,0,0,0,0,1
10,49056,0.0,62,39.209518,-7.034139e+00,0,60,43,345,1,...,0,1,0,0,0,0,0,0,0,1
11,50409,200.0,1062,35.770258,-1.057417e+01,0,10,5,250,1,...,0,0,0,0,0,0,1,0,0,1
12,36957,0.0,0,33.798106,-3.290194e+00,0,17,2,0,1,...,0,0,0,0,0,0,1,0,0,1
13,50495,0.0,1368,37.092574,-3.181783e+00,0,3,7,1,1,...,0,0,0,0,0,0,0,1,0,1
14,53752,0.0,0,34.364073,-3.629333e+00,0,17,6,0,1,...,0,0,0,0,0,0,1,0,0,1
15,61848,0.0,1645,31.444121,-8.274962e+00,0,15,2,200,1,...,0,0,0,0,1,0,0,0,0,1
16,48451,500.0,1703,34.642439,-9.106185e+00,0,11,4,35,1,...,0,0,0,0,0,1,0,0,0,1
17,58155,0.0,1656,34.569266,-9.085515e+00,0,11,4,50,1,...,0,0,0,0,0,1,0,0,0,1
18,34169,0.0,1162,32.920154,-1.947868e+00,0,19,1,1000,1,...,0,0,0,0,1,0,0,0,0,1
19,18274,500.0,1763,34.508967,-9.894412e+00,0,11,5,1,1,...,0,0,0,0,1,0,0,0,0,1
20,48375,200.0,2216,34.473430,-9.594990e+00,0,11,4,4,1,...,0,0,0,0,1,0,0,0,0,1
21,6091,0.0,0,0.000000,-2.000000e-08,0,17,1,0,1,...,0,0,0,0,0,0,1,0,0,1
22,58500,0.0,1510,34.586901,-8.980014e+00,0,11,4,350,1,...,0,0,0,0,0,1,0,0,0,1
23,37862,500.0,672,37.940029,-4.125595e+00,0,3,3,210,1,...,0,0,0,0,0,0,0,0,1,1
24,51058,0.0,1645,29.747066,-4.495568e+00,0,16,3,156,0,...,0,0,0,0,1,0,0,0,0,1
25,22308,0.0,1273,37.422751,-3.317536e+00,0,3,4,140,1,...,0,0,0,0,1,0,0,0,0,1
26,55012,500.0,200,39.370777,-9.942532e+00,0,80,23,260,0,...,0,0,0,0,1,0,0,0,0,1
27,20145,0.0,0,31.104257,-1.735361e+00,0,18,1,0,1,...,0,0,0,0,1,0,0,0,0,1
28,19685,0.0,1443,37.611126,-3.263526e+00,0,3,1,1,1,...,0,0,0,0,0,0,0,0,0,1
29,69124,0.0,1256,37.061688,-3.191989e+00,0,3,7,1,1,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,52228,0.0,265,38.504640,-1.016990e+01,0,8,3,749,1,...,0,0,0,0,1,0,0,0,0,1
74221,70038,5.0,1322,37.261731,-3.235687e+00,0,3,4,45,1,...,0,0,0,0,0,0,0,1,0,1
74222,25901,50.0,640,39.297410,-1.092504e+01,0,90,33,360,1,...,0,0,0,0,0,0,0,0,0,1
74223,21131,0.0,0,33.918953,-9.298466e+00,0,12,4,0,1,...,1,0,0,0,0,0,0,0,0,1
74224,26580,0.0,574,37.070462,-6.575076e+00,0,5,1,250,1,...,0,0,0,0,1,0,0,0,0,1
74225,66059,0.0,331,38.761961,-1.091314e+01,0,90,63,89,1,...,0,0,0,0,1,0,0,0,0,1
74226,32944,0.0,0,32.243937,-3.311621e+00,0,17,5,0,1,...,0,0,0,0,0,0,1,0,0,1
74227,13686,0.0,0,32.985694,-2.734208e+00,0,19,7,0,1,...,0,0,0,0,1,0,0,0,0,1
74228,8471,50.0,78,39.254272,-7.060921e+00,0,60,43,70,0,...,0,1,0,0,0,0,0,0,0,1
74229,19620,0.0,836,35.227320,-1.103905e+01,0,10,3,80,0,...,0,0,0,0,1,0,0,0,0,1
74230,74162,0.0,1651,37.962243,-4.494348e+00,0,3,3,150,1,...,0,0,0,0,0,0,0,0,1,1
74231,37994,0.0,0,0.000000,-2.000000e-08,0,19,2,0,1,...,0,0,0,0,1,0,0,0,0,1
74232,71151,0.0,1393,36.930169,-3.255077e+00,0,2,7,260,1,...,0,0,0,0,1,0,0,0,0,1
74233,45017,1000.0,1729,34.302104,-9.455737e+00,0,11,3,0,1,...,0,0,0,0,1,0,0,0,0,1
74234,12592,0.0,0,35.840727,-4.633272e+00,0,1,1,0,1,...,0,0,0,0,1,0,0,0,0,1
74235,58693,0.0,0,32.442886,-3.644662e+00,0,17,3,0,1,...,0,0,0,0,1,0,0,0,0,1
74236,57539,0.0,-7,39.140091,-7.477423e+00,0,6,4,40,1,...,0,0,0,0,1,0,0,0,0,1
74237,71252,500.0,1241,30.114667,-4.162845e+00,0,16,2,780,1,...,0,0,0,0,0,0,0,0,1,1
74238,7869,3000.0,2046,34.345525,-9.547077e+00,0,11,3,0,1,...,0,0,0,0,1,0,0,0,0,1
74239,57316,0.0,347,38.613415,-4.815222e+00,0,4,2,300,1,...,0,0,0,0,0,0,0,0,0,1
74240,59757,0.0,1291,35.345384,-9.831170e+00,0,10,2,0,1,...,0,0,0,0,1,0,0,0,0,1
74241,64579,0.0,0,0.000000,-2.000000e-08,0,17,1,0,1,...,0,0,0,0,0,0,1,0,0,1
74242,57731,600.0,808,29.740224,-4.882705e+00,0,16,3,230,1,...,0,0,0,0,0,0,1,0,0,1
74243,65541,0.0,1641,29.768139,-4.480618e+00,0,16,2,1400,1,...,0,0,0,0,0,0,0,0,1,1
74244,68174,0.0,0,34.096878,-3.079689e+00,0,17,2,0,1,...,0,0,0,0,0,0,1,0,0,1
74245,39307,0.0,34,38.852669,-6.582841e+00,0,6,1,20,1,...,0,0,0,0,1,0,0,0,0,1
74246,18990,1000.0,0,37.451633,-5.350428e+00,0,4,7,2960,1,...,0,0,0,0,1,0,0,0,0,1
74247,28749,0.0,1476,34.739804,-4.585587e+00,0,13,2,200,1,...,0,0,0,0,1,0,0,0,0,1
74248,33492,0.0,998,35.432732,-1.058416e+01,0,10,2,150,1,...,0,0,0,0,1,0,0,0,0,1
74249,68707,0.0,481,34.765054,-1.122601e+01,0,10,3,40,1,...,0,0,0,0,1,0,0,0,0,1

In [559]:
data.shape

(74250, 176)

In [560]:
data.columns.values

array(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code',
       'lga', 'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group',
       'extraction_type_class', 'management', 'management_group',
       'payment', 'payment_type', 'water_quality', 'quality_group',
       'quantity', 'quantity_group', 'source', 'source_type',
       'source_class', 'waterpoint_type_group_cattle trough',
       'waterpoint_type_group_communal standpipe',
       'waterpoint_type_group_dam', 'waterpoint_type_group_hand pump',
       'waterpoint_type_group_improved spring',
       'waterpoint_type_group_other', 'waterpoint_type_cattle trough',
       'waterpoint_type_communal standpipe',
       'waterpoint_type_communal standpipe multiple',
       'waterpoint_type_dam', 'waterpoint_type_hand pump',
       'waterpoint_type_improved spring', 'waterpoint_type_other',
       'source_class_groundwater', 'source_class_surface',
       'source_class_unknown', 'source_type_borehole', 'source_type_dam',
       'source_type_other', 'source_type_rainwater harvesting',
       'source_type_river/lake', 'source_type_shallow well',
       'source_type_spring', 'sorurce_dam', 'sorurce_hand dtw',
       'sorurce_lake', 'sorurce_machine dbh', 'sorurce_other',
       'sorurce_rainwater harvesting', 'sorurce_river',
       'sorurce_shallow well', 'sorurce_spring', 'sorurce_unknown',
       'extraction_type_class_gravity', 'extraction_type_class_handpump',
       'extraction_type_class_motorpump', 'extraction_type_class_other',
       'extraction_type_class_rope pump',
       'extraction_type_class_submersible',
       'extraction_type_class_wind-powered', 'management_company',
       'management_other', 'management_other - school',
       'management_parastatal', 'management_private operator',
       'management_trust', 'management_unknown', 'management_vwc',
       'management_water authority', 'management_water board',
       'management_wua', 'management_wug', 'management_group_commercial',
       'management_group_other', 'management_group_parastatal',
       'management_group_unknown', 'management_group_user-group',
       'payment_never pay', 'payment_other', 'payment_pay annually',
       'payment_pay monthly', 'payment_pay per bucket',
       'payment_pay when scheme fails', 'payment_unknown',
       'payment_type_annually', 'payment_type_monthly',
       'payment_type_never pay', 'payment_type_on failure',
       'payment_type_other', 'payment_type_per bucket',
       'payment_type_unknown', 'water_quality_coloured',
       'water_quality_fluoride', 'water_quality_fluoride abandoned',
       'water_quality_milky', 'water_quality_salty',
       'water_quality_salty abandoned', 'water_quality_soft',
       'water_quality_unknown', 'quality_group_colored',
       'quality_group_fluoride', 'quality_group_good',
       'quality_group_milky', 'quality_group_salty',
       'quality_group_unknown', 'quantity_dry', 'quantity_enough',
       'quantity_insufficient', 'quantity_seasonal', 'quantity_unknown',
       'quantity_group_dry', 'quantity_group_enough',
       'quantity_group_insufficient', 'quantity_group_seasonal',
       'quantity_group_unknown', 'extraction_type_afridev',
       'extraction_type_cemo', 'extraction_type_climax',
       'extraction_type_gravity', 'extraction_type_india mark ii',
       'extraction_type_india mark iii', 'extraction_type_ksb',
       'extraction_type_mono', 'extraction_type_nira/tanira',
       'extraction_type_other',
       'extraction_type_other - mkulima/shinyanga',
       'extraction_type_other - play pump',
       'extraction_type_other - rope pump',
       'extraction_type_other - swn 81', 'extraction_type_submersible',
       'extraction_type_swn 80', 'extraction_type_walimi',
       'extraction_type_windmill', 'extraction_type_group_afridev',
       'extraction_type_group_gravity',
       'extraction_type_group_india mark ii',
       'extraction_type_group_india mark iii',
       'extraction_type_group_mono', 'extraction_type_group_nira/tanira',
       'extraction_type_group_other',
       'extraction_type_group_other handpump',
       'extraction_type_group_other motorpump',
       'extraction_type_group_rope pump',
       'extraction_type_group_submersible',
       'extraction_type_group_swn 80',
       'extraction_type_group_wind-powered', 'scheme_management_Company',
       'scheme_management_None', 'scheme_management_Other',
       'scheme_management_Parastatal',
       'scheme_management_Private operator', 'scheme_management_SWC',
       'scheme_management_Trust', 'scheme_management_VWC',
       'scheme_management_WUA', 'scheme_management_WUG',
       'scheme_management_Water Board',
       'scheme_management_Water authority',
       'recorded_by_GeoData Consultants Ltd'], dtype=object)

In [567]:
data

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,...,scheme_management_Private operator,scheme_management_SWC,scheme_management_Trust,scheme_management_VWC,scheme_management_WUA,scheme_management_WUG,scheme_management_Water Board,scheme_management_Water authority,recorded_by_GeoData Consultants Ltd,status_group
0,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,1.0
1,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,Lake Victoria,...,0,0,0,0,0,0,0,0,1,1.0
2,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,Pangani,...,0,0,0,1,0,0,0,0,1,1.0
3,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,...,0,0,0,1,0,0,0,0,1,-1.0
4,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,Lake Victoria,...,0,0,0,1,0,0,0,0,1,1.0
5,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,Pangani,...,0,0,0,1,0,0,0,0,1,1.0
6,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,Internal,...,0,0,0,1,0,0,0,0,1,-1.0
7,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,Lake Tanganyika,...,0,0,0,1,0,0,0,0,1,-1.0
8,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,Lake Tanganyika,...,0,0,0,1,0,0,0,0,1,-1.0
9,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,Lake Victoria,...,0,0,0,1,0,0,0,0,1,1.0
10,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,Wami / Ruvu,...,1,0,0,0,0,0,0,0,1,1.0
11,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,Lake Nyasa,...,0,0,0,0,0,1,0,0,1,1.0
12,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,Internal,...,0,0,0,0,0,1,0,0,1,1.0
13,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,Pangani,...,0,0,0,0,0,0,1,0,1,1.0
14,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,Internal,...,0,0,0,0,0,1,0,0,1,1.0
15,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,Lake Tanganyika,...,0,0,0,1,0,0,0,0,1,1.0
16,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,Rufiji,...,0,0,0,0,1,0,0,0,1,-1.0
17,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,Rufiji,...,0,0,0,0,1,0,0,0,1,-1.0
18,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,Lake Victoria,...,0,0,0,1,0,0,0,0,1,0.0
19,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,1.0
20,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,1.0
21,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,Lake Victoria,...,0,0,0,0,0,1,0,0,1,1.0
22,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,Rufiji,...,0,0,0,0,1,0,0,0,1,0.0
23,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,Pangani,...,0,0,0,0,0,0,0,1,1,1.0
24,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,Lake Tanganyika,...,0,0,0,1,0,0,0,0,1,1.0
25,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,Pangani,...,0,0,0,1,0,0,0,0,1,0.0
26,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,Ruvuma / Southern Coast,...,0,0,0,1,0,0,0,0,1,1.0
27,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,Lake Victoria,...,0,0,0,1,0,0,0,0,1,1.0
28,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,Pangani,...,0,0,0,0,0,0,0,0,1,-1.0
29,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,Pangani,...,0,0,0,0,0,0,1,0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74220,0.0,2013-01-27,Dbfpe,265,DBFPE,38.504640,-1.016990e+01,Shule Ya Msingi Mayaka,0,Ruvuma / Southern Coast,...,0,0,0,1,0,0,0,0,1,NaN
74221,5.0,2013-03-29,Ces (gmbh),1322,DWE,37.261731,-3.235687e+00,Kwa Leonard Soka,0,Pangani,...,0,0,0,0,0,0,1,0,1,NaN
74222,50.0,2013-01-22,Lga,640,LGA,39.297410,-1.092504e+01,Tangini,0,Ruvuma / Southern Coast,...,0,0,0,0,0,0,0,0,1,NaN
74223,0.0,2011-04-03,Government Of Tanzania,0,DWE,33.918953,-9.298466e+00,Ndubi,0,Lake Nyasa,...,0,0,0,0,0,0,0,0,1,NaN
74224,0.0,2011-04-20,Po,574,Po,37.070462,-6.575076e+00,Mwanji,0,Wami / Ruvu,...,0,0,0,1,0,0,0,0,1,NaN
74225,0.0,2013-02-02,Fin Water,331,FIN WATER,38.761961,-1.091314e+01,Mkwajuni,0,Ruvuma / Southern Coast,...,0,0,0,1,0,0,0,0,1,NaN
74226,0.0,2012-10-24,World Vision,0,World vision,32.243937,-3.311621e+00,Umoja,0,Lake Tanganyika,...,0,0,0,0,0,1,0,0,1,NaN
74227,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,Lake Victoria,...,0,0,0,1,0,0,0,0,1,NaN
74228,50.0,2011-02-20,Private,78,Private,39.254272,-7.060921e+00,Mkopi,0,Wami / Ruvu,...,1,0,0,0,0,0,0,0,1,NaN
74229,0.0,2013-01-03,Government Of Tanzania,836,Government,35.227320,-1.103905e+01,Kituo Ch Afya,0,Ruvuma / Southern Coast,...,0,0,0,1,0,0,0,0,1,NaN
74230,0.0,2013-03-19,Tcrs,1651,TCRS,37.962243,-4.494348e+00,Kwa Andrew,0,Pangani,...,0,0,0,0,0,0,0,1,1,NaN
74231,0.0,2012-10-26,Hesawa,0,DWE,0.000000,-2.000000e-08,Kwa Masilili,0,Lake Victoria,...,0,0,0,1,0,0,0,0,1,NaN
74232,0.0,2013-03-25,Kkkt,1393,KKKT,36.930169,-3.255077e+00,Tankini,0,Pangani,...,0,0,0,1,0,0,0,0,1,NaN
74233,1000.0,2011-03-05,Kkkt,1729,Commu,34.302104,-9.455737e+00,none,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,NaN
74234,0.0,2011-03-27,Kirde,0,DWE,35.840727,-4.633272e+00,Kwa Mrangi,0,Internal,...,0,0,0,1,0,0,0,0,1,NaN
74235,0.0,2013-01-25,Rwssp,0,DWE,32.442886,-3.644662e+00,Busangi,0,Lake Tanganyika,...,0,0,0,1,0,0,0,0,1,NaN
74236,0.0,2011-03-18,Amref,-7,AMREF,39.140091,-7.477423e+00,Nyamalonda,0,Rufiji,...,0,0,0,1,0,0,0,0,1,NaN
74237,500.0,2013-02-10,Tasaf,1241,TASAF,30.114667,-4.162845e+00,Pentecoste Church,0,Lake Tanganyika,...,0,0,0,0,0,0,0,1,1,NaN
74238,3000.0,2011-03-11,Kkkt,2046,Commu,34.345525,-9.547077e+00,none,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,NaN
74239,0.0,2011-03-11,Devon Aid Korogwe,347,Local technician,38.613415,-4.815222e+00,Jahiya,0,Pangani,...,0,0,0,0,0,0,0,0,1,NaN
74240,0.0,2013-02-24,Villagers,1291,Villagers,35.345384,-9.831170e+00,Kwa Reonard,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,NaN
74241,0.0,2012-10-26,Dwsp,0,DWE,0.000000,-2.000000e-08,Iguna,0,Lake Victoria,...,0,0,0,0,0,1,0,0,1,NaN
74242,600.0,2013-01-27,Isf,808,DWE,29.740224,-4.882705e+00,Hongera,0,Lake Tanganyika,...,0,0,0,0,0,1,0,0,1,NaN
74243,0.0,2013-02-04,Oxfarm,1641,OXFARM,29.768139,-4.480618e+00,Mwandami,0,Lake Tanganyika,...,0,0,0,0,0,0,0,1,1,NaN
74244,0.0,2012-11-07,Netherlands,0,DWE,34.096878,-3.079689e+00,Ikanayugu,0,Lake Victoria,...,0,0,0,0,0,1,0,0,1,NaN
74245,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841e+00,Kwambwezi,0,Wami / Ruvu,...,0,0,0,1,0,0,0,0,1,NaN
74246,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428e+00,Bonde La Mkondoa,0,Pangani,...,0,0,0,1,0,0,0,0,1,NaN
74247,0.0,2013-03-04,Government Of Tanzania,1476,DWE,34.739804,-4.585587e+00,Bwawani,0,Internal,...,0,0,0,1,0,0,0,0,1,NaN
74248,0.0,2013-02-18,Germany,998,DWE,35.432732,-1.058416e+01,Kwa John,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,NaN
74249,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-1.122601e+01,Kwa Mzee Chagala,0,Lake Nyasa,...,0,0,0,1,0,0,0,0,1,NaN

In [571]:
# 查看各个特征与标签之间的相关性
label = pd.read_csv('train_label.csv')
label_mapDict = {'functional':1,'non functional':-1,'functional needs repair':0}
label['status_group'] = label['status_group'].map(label_mapDict)

data['status_group'] = label['status_group']

corrDf = data.corr()
corrDf

,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,public_meeting,permit,...,scheme_management_Private operator,scheme_management_SWC,scheme_management_Trust,scheme_management_VWC,scheme_management_WUA,scheme_management_WUG,scheme_management_Water Board,scheme_management_Water authority,recorded_by_GeoData Consultants Ltd,status_group
amount_tsh,1.000000,0.079851,0.023048,-0.055923,0.005384,-0.027122,-0.024201,0.018385,0.017228,0.024746,...,-0.003845,-0.002375,-0.003551,-0.010016,0.045963,-0.020276,-0.007033,0.005909,NaN,0.053702
gps_height,0.079851,1.000000,0.149071,-0.037621,0.008042,-0.182366,-0.170897,0.134373,0.035810,0.079887,...,-0.078983,-0.039723,-0.007412,-0.055324,0.110283,-0.137514,0.107982,0.074170,NaN,0.114029
longitude,0.023048,0.149071,1.000000,-0.426643,0.024640,0.032260,0.150908,0.087439,0.024860,0.099189,...,0.070397,0.032928,0.010563,0.081454,0.054865,-0.297857,0.097643,-0.017217,NaN,-0.004366
latitude,-0.055923,-0.037621,-0.426643,1.000000,0.006086,-0.217501,-0.200048,-0.022534,0.004936,0.067702,...,-0.009517,-0.016597,-0.009305,-0.198608,-0.089023,0.223728,0.049233,0.062380,NaN,0.014547
num_private,0.005384,0.008042,0.024640,0.006086,1.000000,-0.021277,-0.005264,0.003449,0.009721,0.011610,...,0.005059,-0.001604,-0.001312,-0.003608,-0.008800,-0.011507,-0.006160,0.025759,NaN,0.005021
region_code,-0.027122,-0.182366,0.032260,-0.217501,-0.021277,1.000000,0.680393,0.094665,-0.018771,-0.026494,...,0.025887,-0.019230,0.023147,0.108061,-0.050535,0.016084,-0.120582,-0.050025,NaN,-0.108640
district_code,-0.024201,-0.170897,0.150908,-0.200048,-0.005264,0.680393,1.000000,0.062749,0.011765,-0.069733,...,0.081762,-0.011108,0.044518,0.097334,-0.027714,-0.065557,-0.019597,-0.068178,NaN,-0.065687
population,0.018385,0.134373,0.087439,-0.022534,0.003449,0.094665,0.062749,1.000000,0.003128,-0.034901,...,0.036152,-0.008268,0.004065,-0.031649,-0.024120,-0.029332,-0.015703,0.076354,NaN,0.017759
public_meeting,0.017228,0.035810,0.024860,0.004936,0.009721,-0.018771,0.011765,0.003128,1.000000,0.120838,...,-0.103652,0.012866,-0.010205,0.105840,-0.015361,-0.013571,-0.005554,0.028658,NaN,0.067004
permit,0.024746,0.079887,0.099189,0.067702,0.011610,-0.026494,-0.069733,-0.034901,0.120838,1.000000,...,-0.105460,-0.060747,-0.007005,0.022962,0.068282,-0.188375,0.114047,0.049536,NaN,0.031699
construction_year,0.070927,0.658344,0.396858,-0.247557,0.027228,0.031397,0.047892,0.263189,0.023501,0.078474,...,0.050266,0.029944,0.017894,-0.078594,0.099641,-0.186364,0.131628,0.072889,NaN,0.043342
waterpoint_type_group_cattle trough,-0.004793,0.026871,0.015984,0.029218,-0.001803,-0.027390,-0.005020,0.048810,0.012122,0.015256,...,-0.003802,-0.001833,-0.001585,0.017704,-0.008678,-0.006500,-0.009950,0.002625,NaN,0.014283
waterpoint_type_group_communal standpipe,0.041269,0.241085,0.200008,-0.157725,0.024266,-0.149063,-0.056970,-0.032105,0.062006,0.137496,...,0.031510,-0.009823,0.012750,-0.085061,0.151149,-0.249256,0.166820,0.100233,NaN,0.097247
waterpoint_type_group_dam,-0.001138,-0.006159,0.005816,0.003534,-0.000416,-0.006012,0.000938,0.025492,-0.001240,0.006961,...,-0.001400,-0.000423,-0.000366,0.001480,-0.002326,-0.003214,-0.002296,0.003296,NaN,0.006349
waterpoint_type_group_hand pump,-0.021137,-0.201157,-0.209637,0.100601,-0.018676,0.076406,0.001741,0.024474,-0.025608,-0.122165,...,-0.040108,-0.016890,-0.011013,0.027912,-0.116086,0.276155,-0.137078,-0.083407,NaN,0.092294
waterpoint_type_group_improved spring,-0.005744,0.000683,-0.040869,0.105288,-0.003746,0.014916,-0.029942,0.009230,0.026161,-0.005553,...,-0.015425,-0.004660,-0.004029,0.046772,-0.025077,-0.032042,-0.025297,0.028964,NaN,0.046978
waterpoint_type_group_other,-0.031719,-0.091559,0.002502,0.060221,-0.009491,0.123416,0.099601,0.003792,-0.072172,-0.039460,...,0.015063,0.042414,-0.002375,0.074566,-0.059217,0.003107,-0.053017,-0.047795,NaN,-0.310295
waterpoint_type_cattle trough,-0.004793,0.026871,0.015984,0.029218,-0.001803,-0.027390,-0.005020,0.048810,0.012122,0.015256,...,-0.003802,-0.001833,-0.001585,0.017704,-0.008678,-0.006500,-0.009950,0.002625,NaN,0.014283
waterpoint_type_communal standpipe,0.043573,0.245630,0.181921,-0.169395,0.024660,-0.213258,-0.077927,-0.066164,0.043997,0.139004,...,0.028240,-0.001339,0.011384,-0.071652,0.141752,-0.223262,0.156605,0.047502,NaN,0.165314
waterpoint_type_communal standpipe multiple,-0.004669,-0.012589,0.025558,0.022561,-0.001161,0.108893,0.035724,0.056779,0.028351,-0.005395,...,0.004720,-0.013766,0.001981,-0.020287,0.012278,-0.037539,0.013295,0.084732,NaN,-0.114094
waterpoint_type_dam,-0.001138,-0.006159,0.005816,0.003534,-0.000416,-0.006012,0.000938,0.025492,-0.001240,0.006961,...,-0.001400,-0.000423,-0.000366,0.001480,-0.002326,-0.003214,-0.002296,0.003296,NaN,0.006349
waterpoint_type_hand pump,-0.021137,-0.201157,-0.209637,0.100601,-0.018676,0.076406,0.001741,0.024474,-0.025608,-0.122165,...,-0.040108,-0.016890,-0.011013,0.027912,-0.116086,0.276155,-0.137078,-0.083407,NaN,0.092294
waterpoint_type_improved spring,-0.005744,0.000683,-0.040869,0.105288,-0.003746,0.014916,-0.029942,0.009230,0.026161,-0.005553,...,-0.015425,-0.004660,-0.004029,0.046772,-0.025077,-0.032042,-0.025297,0.028964,NaN,0.046978
waterpoint_type_other,-0.031719,-0.091559,0.002502,0.060221,-0.009491,0.123416,0.099601,0.003792,-0.072172,-0.039460,...,0.015063,0.042414,-0.002375,0.074566,-0.059217,0.003107,-0.053017,-0.047795,NaN,-0.310295
source_class_groundwater,-0.038657,-0.046710,-0.020874,0.045690,-0.006664,0.076912,0.051898,-0.033530,0.055541,-0.109288,...,0.008466,0.022167,-0.013660,0.148230,-0.185904,0.117182,-0.013546,-0.106714,NaN,-0.027706
source_class_surface,0.039788,0.051916,0.019426,-0.049413,0.002418,-0.075162,-0.053153,0.034019,-0.054539,0.107880,...,-0.015312,-0.021873,0.013237,-0.150761,0.189631,-0.117315,0.014286,0.109015,NaN,0.027958
source_class_unknown,-0.005177,-0.029721,0.009790,0.020699,0.026247,-0.014144,0.005340,-0.001485,-0.008612,0.013504,...,0.041456,-0.002791,0.003200,0.008817,-0.014431,-0.004444,-0.003914,-0.009279,NaN,-0.000300
source_type_borehole,0.001423,-0.065622,0.073825,-0.089835,0.008648,0.137693,0.079377,0.068035,0.006816,-0.092837,...,0.107926,0.066323,0.013851,0.048535,-0.049448,-0.058178,-0.015002,0.011601,NaN,-0.066367
source_type_dam,-0.006271,-0.047533,0.007379,0.038265,-0.003845,-0.004167,-0.014614,0.017645,-0.034500,-0.013062,...,0.016345,-0.004357,0.003472,-0.032939,-0.016812,-0.026812,-0.019428,0.111466,NaN,-0.039043
source_type_other,-0.005177,-0.029721,0.009790,0.020699,0.026247,-0.014144,0.005340,-0.001485,-0.008612,0.013504,...,0.041456,-0.002791,0.003200,0.008817,-0.014431,-0.004444,-0.003914,-0.009279,NaN,-0.000300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
extraction_type_swn 80,-0.001276,-0.061670,-0.035291,-0.045680,-0.007360,-0.048818,-0.053660,0.013479,0.017951,-0.018730,...,-0.027426,-0.010454,-0.005859,0.049832,-0.049651,0.087424,-0.053305,-0.055072,NaN,0.010238
extraction_type_walimi,-0.003036,-0.025010,-0.077394,0.038160,-0.001140,0.002763,-0.010999,-0.010707,0.002381,-0.026015,...,-0.003835,-0.001158,-0.001002,-0.036712,-0.006373,0.076746,-0.006289,-0.006763,NaN,0.001482
extraction_type_windmill,-0.004334,-0.004961,0.007519,0.011703,-0.001815,-0.011783,-0.002770,0.021614,-0.003333,0.000739,...,0.018642,-0.001845,0.015345,-0.007637,0.003813,-0.006642,-0.010016,0.001142,NaN,-0.011427
extraction_type_group_afridev,-0.000631,-0.032546,-0.043549,0.086576,-0.003840,0.023743,0.011233,0.026326,0.004219,0.017978,...,0.002136,-0.001282,0.005103,0.030594,-0.030689,0.022401,-0.037964,-0.014162,NaN,0.040746
extraction_type_group_gravity,0.028236,0.362284,0.114707,-0.080374,-0.002020,-0.192693,-0.079792,-0.063145,0.076497,0.154955,...,-0.088962,-0.035364,0.000605,-0.030700,0.114502,-0.197946,0.156980,0.087019,NaN,0.134059
extraction_type_group_india mark ii,0.014799,-0.018900,-0.036307,-0.051740,-0.006989,0.088220,0.059455,0.056348,-0.020921,-0.040397,...,-0.012900,-0.000030,0.000478,0.057119,-0.041433,-0.013494,-0.045284,-0.021523,NaN,0.017444
extraction_type_group_india mark iii,-0.004349,-0.030487,-0.005537,-0.003311,-0.001710,0.063145,0.100600,0.016217,0.010177,-0.034258,...,0.015729,-0.001739,-0.001503,0.005917,-0.009565,0.011400,-0.009438,-0.010150,NaN,-0.010729
extraction_type_group_mono,-0.001322,-0.104739,0.051657,-0.020891,0.009062,0.042297,0.056578,-0.026479,0.018509,-0.014000,...,0.010948,0.090621,0.027535,0.054088,-0.038793,-0.050281,-0.037679,-0.010054,NaN,-0.084968
extraction_type_group_nira/tanira,-0.033864,-0.206382,-0.201482,0.152137,-0.011178,0.067945,0.003129,-0.030469,-0.029737,-0.119875,...,-0.028131,-0.006642,-0.012948,-0.039358,-0.071864,0.296699,-0.086793,-0.067654,NaN,0.104755
extraction_type_group_other,-0.028378,-0.103220,-0.037115,0.040929,-0.011044,0.117646,0.051738,0.023474,-0.047994,-0.022310,...,0.013148,-0.006821,-0.002504,0.063985,-0.071957,0.005071,-0.069406,-0.002637,NaN,-0.295936
extraction_type_group_other handpump,0.006446,-0.003140,-0.022313,-0.007536,-0.003073,-0.001826,-0.001466,-0.003934,-0.014218,-0.050943,...,-0.009180,-0.003170,-0.002741,0.011006,-0.017442,0.021501,-0.017211,-0.013095,NaN,-0.013132
extraction_type_group_other motorpump,0.005182,-0.037947,0.007871,0.020292,-0.001797,-0.028800,-0.017128,-0.014148,0.012067,-0.051257,...,0.023494,-0.001827,-0.001579,0.019500,-0.010050,-0.009624,-0.009917,-0.010665,NaN,-0.010327
extraction_type_group_rope pump,-0.003860,0.062328,0.009004,0.011888,-0.003531,-0.003553,-0.002697,0.006272,-0.015080,-0.024835,...,0.005565,-0.003589,-0.003103,-0.039770,0.012015,-0.001659,-0.007065,-0.007953,NaN,0.016410
extraction_type_group_submersible,0.013806,-0.105205,0.118659,-0.051924,0.035708,0.053845,0.021167,0.065785,-0.052700,-0.021330,...,0.176127,0.019608,-0.002038,-0.096167,0.081497,-0.058538,0.042697,0.017966,NaN,-0.014484
extraction_type_group_swn 80,-0.001276,-0.061670,-0.035291,-0.045680,-0.007360,-0.048818,-0.053660,0.013479,0.017951,-0.018730,...,-0.027426,-0.010454,-0.005859,0.049832,-0.049651,0.087424,-0.053305,-0.055072,NaN,0.010238
extraction_type_group_wind-powered,-0.004334,-0.004961,0.007519,0.011703,-0.001815,-0.011783,-0.002770,0.021614,-0.003333,0.000739,...,0.018642,-0.001845,0.015345,-0.007637,0.003813,-0.006642,-0.010016,0.001142,NaN,-0.011427
scheme_management_Company,0.009262,0.037740,0.074721,0.044069,-0.003147,-0.080444,-0.057813,-0.032143,-0.006818,0.084164,...,-0.018288,-0.005524,-0.004777,-0.199381,-0.030394,-0.041993,-0.029992,-0.032255,NaN,-0.016665
scheme_management_None,-0.000339,-0.003585,0.002991,-0.001743,-0.000147,-0.001732,-0.001001,-0.001096,0.001159,-0.005473,...,-0.000495,-0.000149,-0.000129,-0.005395,-0.000822,-0.001136,-0.000812,-0.000873,NaN,0.003634
scheme_management_Other,-0.011165,0.077882,0.004656,0.063089,-0.004551,0.010261,-0.025785,0.107327,-0.151504,0.036430,...,-0.015724,-0.004750,-0.004107,-0.171425,-0.026133,-0.036105,-0.025787,-0.027732,NaN,0.007907
scheme_management_Parastatal,0.009084,-0.000298,-0.022021,0.077174,0.016148,-0.007507,-0.015730,0.009714,-0.092932,-0.035487,...,-0.023140,-0.006990,-0.006044,-0.252285,-0.038459,-0.053136,-0.037950,-0.040813,NaN,0.020010
scheme_management_Private operator,-0.003845,-0.078983,0.070397,-0.009517,0.005059,0.025887,0.081762,0.036152,-0.103652,-0.105460,...,1.000000,-0.005493,-0.004750,-0.198242,-0.030221,-0.041753,-0.029821,-0.032070,NaN,0.033312
scheme_management_SWC,-0.002375,-0.039723,0.032928,-0.016597,-0.001604,-0.019230,-0.011108,-0.008268,0.012866,-0.060747,...,-0.005493,1.000000,-0.001435,-0.059886,-0.009129,-0.012613,-0.009008,-0.009688,NaN,-0.031347
scheme_management_Trust,-0.003551,-0.007412,0.010563,-0.009305,-0.001312,0.023147,0.044518,0.004065,-0.010205,-0.007005,...,-0.004750,-0.001435,1.000000,-0.051782,-0.007894,-0.010906,-0.007789,-0.008377,NaN,0.006910
scheme_management_VWC,-0.010016,-0.055324,0.081454,-0.198608,-0.003608,0.108061,0.097334,-0.031649,0.105840,0.022962,...,-0.198242,-0.059886,-0.051782,1.000000,-0.329480,-0.455214,-0.325120,-0.349646,NaN,-0.110894
scheme_management_WUA,0.045963,0.110283,0.054865,-0.089023,-0.008800,-0.050535,-0.027714,-0.024120,-0.015361,0.068282,...,-0.030221,-0.009129,-0.007894,-0.329480,1.000000,-0.069394,-0.049562,-0.053301,NaN,0.073250
scheme_management_WUG,-0.020276,-0.137514,-0.297857,0.223728,-0.011507,0.016084,-0.065557,-0.029332,-0.013571,-0.188375,...,-0.041753,-0.012613,-0.010906,-0.455214,-0.069394,1.000000,-0.068476,-0.073642,NaN,0.040812
scheme_management_Water Board,-0.007033,0.107982,0.097643,0.049233,-0.006160,-0.120582,-0.019597,-0.015703,-0.005554,0.114047,...,-0.029821,-0.009008,-0.007789,-0.325120,-0.049562,-0.068476,1.000000,-0.052596,NaN,0.087127
scheme_management_Water authority,0.005909,0.074170,-0.017217,0.062380,0.025759,-0.050025,-0.068178,0.076354,0.028658,0.049536,...,-0.032070,-0.009688,-0.008377,-0.349646,-0.053301,-0.073642,-0.052596,1.000000,NaN,0.002386
recorded_by_GeoData Consultants Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status_group,0.053702,0.114029,-0.004366,0.014547,0.005021,-0.108640,-0.065687,0.017759,0.067004,0.031699,...,0.033312,-0.031347,0.006910,-0.110894,0.073250,0.040812,0.087127,0.002386,NaN,1.000000

In [572]:

corrDf['status_group'].sort_values(ascending=False)[:50]

status_group                                1.000000
quantity_group_enough                       0.258402
quantity_enough                             0.258402
waterpoint_type_communal standpipe          0.165314
extraction_type_group_gravity               0.134059
extraction_type_class_gravity               0.134059
extraction_type_gravity                     0.134059
quality_group_good                          0.127763
water_quality_soft                          0.127763
payment_pay monthly                         0.116186
payment_type_monthly                        0.116186
gps_height                                  0.114029
payment_type_annually                       0.111307
payment_pay annually                        0.111307
payment_type_per bucket                     0.107686
payment_pay per bucket                      0.107686
source_type_spring                          0.107233
sorurce_spring                              0.107233
extraction_type_class_handpump              0.105952
extraction_type_nira/tanira                 0.104755
extraction_type_group_nira/tanira           0.104755
management_water board                      0.098677
waterpoint_type_group_communal standpipe    0.097247
waterpoint_type_hand pump                   0.092294
waterpoint_type_group_hand pump             0.092294
scheme_management_Water Board               0.087127
scheme_management_WUA                       0.073250
management_private operator                 0.070453
management_wua                              0.067466
public_meeting                              0.067004
amount_tsh                                  0.053702
management_wug                              0.051456
sorurce_river                               0.048718
waterpoint_type_improved spring             0.046978
waterpoint_type_group_improved spring       0.046978
construction_year                           0.043342
payment_type_on failure                     0.042817
payment_pay when scheme fails               0.042817
scheme_management_WUG                       0.040812
extraction_type_group_afridev               0.040746
extraction_type_afridev                     0.040746
sorurce_rainwater harvesting                0.039222
source_type_rainwater harvesting            0.039222
scheme_management_Private operator          0.033312
permit                                      0.031699
source_class_surface                        0.027958
management_group_commercial                 0.027436
quantity_seasonal                           0.026209
quantity_group_seasonal                     0.026209
water_quality_fluoride                      0.025468
Name: status_group, dtype: float64

In [575]:
# 选择相关性大于0.1的特征 作为模型的输入特征
model_features = ['quantity_group_enough'                    
,'quantity_enough'                         
,'waterpoint_type_communal standpipe'         
,'extraction_type_group_gravity'               
,'extraction_type_class_gravity'               
,'extraction_type_gravity'                     
,'quality_group_good'                          
,'water_quality_soft'                          
,'payment_pay monthly'                         
,'payment_type_monthly'                        
,'gps_height'                                  
,'payment_type_annually'                       
,'payment_pay annually'                        
,'payment_type_per bucket'                     
,'payment_pay per bucket'                      
,'source_type_spring'                          
,'sorurce_spring'                              
,'extraction_type_class_handpump'              
,'extraction_type_nira/tanira'                 
,'extraction_type_group_nira/tanira'           
,'management_water board'                      
,'waterpoint_type_group_communal standpipe'    
,'waterpoint_type_hand pump'                   
,'waterpoint_type_group_hand pump'             
,'scheme_management_Water Board'               
,'scheme_management_WUA'                       
,'management_private operator'                 
,'management_wua'                              
,'public_meeting'                              
,'amount_tsh'                                  
,'management_wug'                              
,'sorurce_river'                               
,'waterpoint_type_improved spring'             
,'waterpoint_type_group_improved spring'       
,'construction_year'                           
,'payment_type_on failure'                     
,'payment_pay when scheme fails'               
,'scheme_management_WUG'                       
,'extraction_type_group_afridev'               
,'extraction_type_afridev'                     
,'sorurce_rainwater harvesting'                
,'source_type_rainwater harvesting'            
,'scheme_management_Private operator'          
,'permit'                                      
,'source_class_surface'                        
,'management_group_commercial'                 
,'quantity_seasonal'                           
,'quantity_group_seasonal'                     
,'water_quality_fluoride']

In [578]:

train_size = len(train)
print(train_size)
train_X = data[model_features][:train_size].values
print('训练集大小:',train_X.shape)
pred_X = data[model_features][train_size:].values
print('预测集大小:',pred_X.shape)

59400
训练集大小: (59400, 49)
预测集大小: (14850, 49)

In [586]:
label = pd.read_csv('train_label.csv')
status_groupDf = pd.DataFrame()
status_groupDf= pd.get_dummies(label['status_group'],prefix='status_group')
label = pd.concat([label,status_groupDf],axis=1)
label

,id,status_group,status_group_functional,status_group_functional needs repair,status_group_non functional
0,69572,functional,1,0,0
1,8776,functional,1,0,0
2,34310,functional,1,0,0
3,67743,non functional,0,0,1
4,19728,functional,1,0,0
5,9944,functional,1,0,0
6,19816,non functional,0,0,1
7,54551,non functional,0,0,1
8,53934,non functional,0,0,1
9,46144,functional,1,0,0
10,49056,functional,1,0,0
11,50409,functional,1,0,0
12,36957,functional,1,0,0
13,50495,functional,1,0,0
14,53752,functional,1,0,0
15,61848,functional,1,0,0
16,48451,non functional,0,0,1
17,58155,non functional,0,0,1
18,34169,functional needs repair,0,1,0
19,18274,functional,1,0,0
20,48375,functional,1,0,0
21,6091,functional,1,0,0
22,58500,functional needs repair,0,1,0
23,37862,functional,1,0,0
24,51058,functional,1,0,0
25,22308,functional needs repair,0,1,0
26,55012,functional,1,0,0
27,20145,functional,1,0,0
28,19685,non functional,0,0,1
29,69124,functional,1,0,0
...,...,...,...,...,...
59370,14796,functional,1,0,0
59371,20387,non functional,0,0,1
59372,29940,non functional,0,0,1
59373,15233,functional,1,0,0
59374,49651,functional,1,0,0
59375,50998,functional,1,0,0
59376,34716,non functional,0,0,1
59377,43986,non functional,0,0,1
59378,38067,functional,1,0,0
59379,58255,functional,1,0,0
59380,30647,non functional,0,0,1
59381,67885,non functional,0,0,1
59382,47002,non functional,0,0,1
59383,44616,functional,1,0,0
59384,72148,non functional,0,0,1
59385,34473,functional,1,0,0
59386,34952,functional,1,0,0
59387,26640,functional,1,0,0
59388,72559,functional,1,0,0
59389,30410,functional,1,0,0
59390,13677,functional,1,0,0
59391,44885,non functional,0,0,1
59392,40607,non functional,0,0,1
59393,48348,functional,1,0,0
59394,11164,non functional,0,0,1
59395,60739,functional,1,0,0
59396,27263,functional,1,0,0
59397,37057,functional,1,0,0
59398,31282,functional,1,0,0
59399,26348,functional,1,0,0

In [588]:
y = label[['status_group_functional','status_group_functional needs repair','status_group_non functional']].values
y.shape

(59400, 3)

In [589]:
# Multi_label[:50]
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=uint8)

In [ ]:
# from sklearn import svm
# from sklearn.metrics import roc_curve, auc
# from sklearn.multiclass import OneVsRestClassifier

# model = OneVsRestClassifier(svm.SVC(kernel='linear',random_state=42))
# model.fit(train_X, y)
# model.score(train_X,y)

# """
# 生成的预测值是浮点数(0.0,1.0)
# 要求提交结果为整型(0,1)
# """
# pred_Y = clf.predict(pred_X)
# pred_Y = pred_Y.astype(int)
# # id
# area_id = test['id'].values
# # 数据框: id,预测情况
# predDf = pd.DataFrame({
#     'id':area_id,
#     'status_group':pred_Y
# })
# print(predDf.shape)
# print(predDf.head(10))

# # 保存结果
# predDf.to_csv('Data_Mining_the_Water_Table_lr.csv',index=False)

In [ ]:
# from sklearn.linear_model import RidgeClassifier

# clf = RidgeClassifier()
# clf.fit(train_X,y)
# clf.score(train_X,y)

In [590]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# 0.8694612794612795
model = RandomForestClassifier()
model.fit(train_X,y)
print(model.score(train_X,y))

# param_test1 = {'n_estimators':range(1,101,10)}
# print(param_test1)

# 91
# gsearch1 = GridSearchCV(estimator=RandomForestClassifier(),param_grid=param_test1,scoring='roc_auc',cv=10)
# gsearch1.fit(train_X,y)
# print(gsearch1.best_params_)
# print(gsearch1.best_estimator_)
# print(gsearch1.best_score_)
# print(gsearch1.best_index_)
# print('best accuracy:%f' % gsearch1.best_score_)

# 4
# param_test2 = {'max_features':range(1,11,1)}
# gsearch2 = GridSearchCV(estimator=RandomForestClassifier(n_estimators=91,random_state=10),
#                         param_grid=param_test2,scoring='roc_auc',cv=10)
# gsearch2.fit(train_X,y)
# print(gsearch2.best_params_)
# print(gsearch2.best_estimator_)
# print(gsearch2.best_score_)
# print(gsearch2.best_index_)
# print('best accuracy:%f' % gsearch2.best_score_)

# 12
# param_test3 = {'max_depth':range(10,20,1)}
# gsearch3 = GridSearchCV(estimator=RandomForestClassifier(n_estimators=91,max_features=4,random_state=10),
#                         param_grid=param_test3,scoring='roc_auc',cv=10)
# gsearch3.fit(train_X,y)
# print(gsearch3.best_params_)
# print(gsearch3.best_estimator_)
# print(gsearch3.best_score_)
# print(gsearch3.best_index_)
# print('best accuracy:%f' % gsearch3.best_score_)

# 用最优参数重新训练数据，计算泛化误差
# rf0 = RandomForestClassifier(n_estimators=91,max_features=4,max_depth=12,oob_score=True,random_state=10)
# rf0.fit(train_X,y)
# print(rf0.oob_score_)
# print(" auc accuracy: %f" % rf0.oob_score_)

# """
# 生成的预测值是浮点数(0.0,1.0)
# 要求提交结果为整型(0,1)
# """
pred_Y = model.predict(pred_X)
pred_Y = pred_Y.astype(int)





# # id
# area_id = test['id'].values
# # 数据框: id,预测情况
# predDf = pd.DataFrame({
#     'id':area_id,
#     'status_group':pred_Y
# })
# print(predDf.shape)
# print(predDf.head(10))

# # 保存结果
# predDf.to_csv('Data_Mining_the_Water_Table_RandomForest.csv',index=False)

0.8694612794612795

In [591]:
# ['functional','functional needs repair','non functional']
df = pd.DataFrame(data=pred_Y,columns=['functional','functional needs repair','non functional'])

def get_animal(row):
    for c in df.columns:
        if row[c]==1:
            return c

df.apply(get_animal, axis=1) 

ds = pd.DataFrame()
ds['id'] = test['id'].values
ds['status_group'] = df.apply(get_animal, axis=1)
ds = ds.replace('None',np.nan).fillna(axis=0,method='ffill')
ds.to_csv('Data_Mining_the_Water_Table_RandomForest_v3.csv',index=False)


# s1 = []
# for i in df['functional']:
#     if i == 1:
#         i = 'functional'
#     s1.append(i)
# df['functional'] = s1
    
# s2 = []
# for i in df['functional needs repair']:
#     if i == 1:
#         i = 'functional needs repair'
#     s2.append(i)
# df['functional needs repair'] = s2
    
# s3 = []
# for i in df['non functional']:
#     if i == 1:
#         i = 'non functional'
#     s3.append(i)
# df['non functional'] = s3

# df = df.replace(0,np.nan).values.ravel()
# df = pd.DataFrame(df[pd.notnull(df)], columns=['status_group'])
# df 

# pd.DataFrame([x for x in np.where(df ==1, df.columns,'').flatten().tolist() if len(x) >0],columns= (["status_group"]) )


# df['id'] = test['id'].values
# df['status_group'] = pd.DataFrame([x for x in np.where(df ==1, df.columns,'').flatten().tolist() if len(x) >0],columns= (["status_group"]) )
# df[:50]
# # df.drop('functional',axis=1)
# df.drop('functional needs repair',axis=1)
# df.drop('non functional',axis=1)

In [ ]:
df = pd.DataFrame({"monkey":[0,1,0,0,0],"rabbit":[1,0,0,0,0],"fox":[0,0,1,0,0]})

animals = pd.DataFrame({"monkey":[0,1,0,0,0],"rabbit":[1,0,0,0,0],"fox":[0,0,1,0,0]})

def get_animal(row):
    for c in animals.columns:
        if row[c]==1:
            return c

df.apply(get_animal, axis=1)